### ISSUE TITLE
Develop methods to purge and restore project settings and data

### ISSUE THREAD

**Issue by nutterb** [vubiostat/redcapAPI#104]
In the course of testing, I'm finding that classical and longitudinal projects will behave differently. Maintaining a collection of test projects (and ensuring everyone doing development has access to them) to cover all of the different use cases is onerous. With the export/import methods we have established, we should be able to purge a project of its data and settings and then restore the settings and data of a different project. This would allow us to conduct testing on a diverse set of project configurations with only one REDCap project to manage. It would also make it possible for outside contributors to run the same suite of tests we are using.

QUESTION 1: are `purgeProject` and `restoreProject` reasonable names for these methods?

QUESTION 2: Should they be exported? I'm leaning toward no. devtools::test will load all of the unexported methods for use in testing, so we can use it for testing without it being exported. 

QUESTION 3: What else am I missing?

### purge project interface

Each type of data that can be deleted has a logical the user can set to delete that element.  It might need a `purge_all` override/shortcut.  We should probably consider excluding `users`, as deleting all the users would lock everyone out of a project.

```
purgeProject.redcapApiConnection <- function(object, 
                                             arms           = FALSE, 
                                             events         = FALSE, 
                                             users          = FALSE, 
                                             user_roles     = FALSE, 
                                             dags           = FALSE, 
                                             records        = FALSE, 
                                             error_handling = getOption("redcap_error_handling"), 
                                             config         = list())
```

### restore project interface

User can provide either a file or a data frame to each of the arguments that gives the settings to import. (I've included placeholders for the methods we haven't developed yet and should probably include a message that they are not yet available)

```
restoreProject.redcapApiConnection <- function(object, 
                                               project_information   = NULL,
                                               arms                  = NULL, 
                                               events                = NULL, 
                                               meta_data             = NULL,
                                               mappings              = NULL, 
                                               repeating_instruments = NULL,
                                               users                 = NULL, 
                                               user_roles            = NULL, 
                                               user_role_assignments = NULL,
                                               dags                  = NULL, 
                                               dag_assignments       = NULL,
                                               records               = NULL, 
                                               error_handling        = getOption("redcap_error_handling"), 
                                               config                = list())
```

And a shortcut function that allows us to pass a list with the elements we want to push. This would allow us to store project configurations in a list and easily push them to a project. I think we'll appreciate the ability to keep all of the elements stored together, especially if the number of projects we use grows larger than 2.

```
restoreProject.list <- function(object, rcon, ...){
  restoreProject.redcapApiConnection(rcon, 
      project_information = object$project_information, 
      .......... # and so on
}
```

### preserve project

I suspect we may also want a utility like  `preserveProject <- function(rcon)` that saves all of the project elements into a list

**Comment by spgarbet** [comment]
Merged #110
