### ISSUE TITLE
importRecords error

### ISSUE THREAD

**Issue by sbrown-iu** [vubiostat/redcapAPI#108]
Receiving the following error message when attempting to import records. Have isolated the issue to be the date column in the data frame. Removing the date column results in successful upload. I have attempted importing the column as a character, Date object, POSIXct object, but keep receiving the following error message every time. Any guidance would be appreciated. This is code that has worked until recently. Have triple-checked field name is the same as in REDCap.

Error in `[.data.frame`(data, date_vars) : undefined columns selected

Appreciate all of the work going into this package!

**Comment by nutterb** [comment]
It looks like I ran into something similar while making some changes last week.  ([see here](https://github.com/vubiostat/redcapAPI/commit/72acd74cf6da8f0429fb538bbb98bd794ceadb1a#diff-f18d9fc3a7bbea0bad16fb4f9825490671ff4ec5868ce6544a71fc71c8975e26R233))

Any chance you could use our current version on Github (2.7.0) `devtools::install_github("vubiostat/redcapAPI")`? 

If you're already using 2.7.0, could you tell us what version of REDCap you are using and maybe share the row of the data dictionary that identifies your date?
