### ISSUE TITLE
2.7.1 Release

### ISSUE THREAD

**Issue by spgarbet** [vubiostat/redcapAPI#117]
The planned 2.7.0 release is packed with goodies at present. This is the punch list for when we release.

Remaining Work:

~~#44 widen repeating~~
~~#89 need a solid vignette to include~~
~~#106 bulk records~~
~~#115 exportReportsTyped~~
~~#122 exportRecordsTyped forms argument~~
~~#137 is NA helper function~~

With this finished we should start the QA process to get a CRAN release done.

**Comment by nutterb** [comment]
I've got a draft ready for #115 . I just need to finalize tests and check.  Hopefully I can get that done today.

**Comment by spgarbet** [comment]
I hate squeezing another one in last minute, but #122 seems important enough.

**Comment by spgarbet** [comment]
I think #137 resolution is really the only thing holding us back from just releasing this. We need it out before/around the time of Savannah's presentation. Remaining issues could be version bumps.

**Comment by spgarbet** [comment]
I'm thinking we need to make the cran release 2.7.1 because 2.7.0 has been in use too long.

**Comment by spgarbet** [comment]
Win-Builder Devel Check

* using log directory 'd:/RCompile/CRANguest/R-devel/redcapAPI.Rcheck'
* using R Under development (unstable) (2023-06-09 r84528 ucrt)
* using platform: x86_64-w64-mingw32
* R was compiled by
    gcc.exe (GCC) 12.2.0
    GNU Fortran (GCC) 12.2.0
* running under: Windows Server 2022 x64 (build 20348)
* using session charset: UTF-8
* checking for file 'redcapAPI/DESCRIPTION' ... OK
* checking extension type ... Package
* this is package 'redcapAPI' version '2.7.1'
* package encoding: UTF-8
* checking CRAN incoming feasibility ... Note_to_CRAN_maintainers
Maintainer: 'Shawn Garbett <shawn.garbett@vumc.org>'
* checking package namespace information ... OK
* checking package dependencies ... OK
* checking if this is a source package ... OK
* checking if there is a namespace ... OK
* checking for hidden files and directories ... OK
* checking for portable file names ... OK
* checking whether package 'redcapAPI' can be installed ... OK
* checking installed package size ... OK
* checking package directory ... OK
* checking for future file timestamps ... OK
* checking 'build' directory ... OK
* checking DESCRIPTION meta-information ... OK
* checking top-level files ... OK
* checking for left-over files ... OK
* checking index information ... OK
* checking package subdirectories ... OK
* checking R files for non-ASCII characters ... OK
* checking R files for syntax errors ... OK
* checking whether the package can be loaded ... OK
* checking whether the package can be loaded with stated dependencies ... OK
* checking whether the package can be unloaded cleanly ... OK
* checking whether the namespace can be loaded with stated dependencies ... OK
* checking whether the namespace can be unloaded cleanly ... OK
* checking loading without being on the library search path ... OK
* checking startup messages can be suppressed ... OK
* checking use of S3 registration ... OK
* checking dependencies in R code ... OK
* checking S3 generic/method consistency ... OK
* checking replacement functions ... OK
* checking foreign function calls ... OK
* checking R code for possible problems ... [13s] OK
* checking Rd files ... OK
* checking Rd metadata ... OK
* checking Rd line widths ... OK
* checking Rd cross-references ... OK
* checking for missing documentation entries ... OK
* checking for code/documentation mismatches ... OK
* checking Rd \usage sections ... OK
* checking Rd contents ... OK
* checking for unstated dependencies in examples ... OK
* checking sizes of PDF files under 'inst/doc' ... OK
* checking installed files from 'inst/doc' ... OK
* checking files in 'vignettes' ... OK
* checking examples ... OK
* checking for unstated dependencies in vignettes ... OK
* checking package vignettes in 'inst/doc' ... OK
* checking re-building of vignette outputs ... OK
* checking PDF version of manual ... [16s] OK
* checking HTML version of manual ... [13s] OK
* DONE
Status: OK

**Comment by spgarbet** [comment]
Submitted.
