### ISSUE TITLE
exportRecordsTyped forms argument

### ISSUE THREAD

**Issue by spgarbet** [vubiostat/redcapAPI#122]
When specifying the forms argument to `exportRecordsTyped` we get back the faithful return from the REDCap call.

```
> read.csv(text = as.character(response), na.strings = "")
   treatment randomization_complete
1         NA                      0
2         NA                      0
3          1                      0
4         NA                      0

> head(exportRecordsTyped(rcon, forms="randomization"))
  treatment randomization_complete
1      <NA>             Incomplete
2      <NA>             Incomplete
3   Control             Incomplete
4      <NA>             Incomplete
5      <NA>             Incomplete
6      <NA>             Incomplete
> 
> response <- makeApiCall(
+     rcon,
+     body = c(list(content = 'record',
+                   action = 'export',
+                   format = 'csv'),
+              vectorToApiBodyList("randomization", "forms")))
> 
> head(read.csv(text = as.character(response), na.strings = ""))
  treatment randomization_complete
1        NA                      0
2        NA                      0
3         1                      0
4        NA                      0
5        NA                      0
6        NA                      0
```

This is however not useful. A user needs the record_id, redcap_event_name, redcap_repeat_instance and/or redcap_repeat_instrument fields to make sense of the data, especially when widening. This prevents #44 from being a useful post process with exportBulkRecords. 

Do we request a change upstream with the REDCap team or do we try to handle it with custom code that tries to pull the right events? 

We need it to export all the relevant fields, in this case we would expect the output to match this: 
`exportRecordsTyped(rcon, fields=c("record_id", "redcap_event_name", "redcap_repeat_instance", "redcap_repeat_instrument", "treatment", "randomization_complete"))`.

In the code solution, we'd have to intercept the forms argument and build our own fields list custom from the meta data.

**Comment by spgarbet** [comment]
If there is a way to export just the system columns, when forms is used we could cbind them right at the final return. This would probably be the easiest solution.

**Comment by nutterb** [comment]
It looks like adding `record_id` is sufficient to make the rest of the system fields come through. 

I'm working on a patch that will forcefully include the record ID field and the secondary ID field (if one is specified)

```
response <- 
  makeApiCall(rcon, 
              body = c(list(content = 'record', 
                            action = 'export', 
                            format = 'csv'), 
                       redcapAPI:::vectorToApiBodyList("randomization", "forms"), 
                       redcapAPI:::vectorToApiBodyList("record_id", "fields")))
read.csv(text = as.character(response), 
         na.strings = "")
```

**Comment by nutterb** [comment]
Ran into this: 

`exportRecordsTyped(rcon, fields = "record_id")` returns the record ID and all of the system fields. 

`exportRecordsTyped(rcon, fields = c("record_id", "redcap_event_name")` returns ONLY the record ID and redcap_event_name. 

We currently have it coded in https://github.com/vubiostat/redcapAPI/blob/main/R/exportRecordsTyped.R#L382-L389 so that if the user specifies any of the system fields in `fields`, they only receive the requested system fields. I think the assumption was that if they are aware enough of system fields to only request a subset of those fields, we should honor their request. 

Is this behavior we want to keep?  One the one hand, we could simply push all of the system fields out on every call, since they are all crucial identifiers. One the other, it's good to honor the user request.  If we keep this behavior, I need to document it better.

**Comment by spgarbet** [comment]
I think what we should do is as follows:

* Drop the `forms` argument as it doesn't do anything useful for the user. A user could still specify it via config. 
* Add a `form` argument that only retrieves data relevant for that form. If the fields argument is also specified, respect that. If the fields argument isn't a subset of the form fields then throw a warning. Then using the definition of the form, drop the rows that aren't part of that form and correct the "invalid" if attached as well to that subset. 

This is the crux of what users really want from a form argument. forms as plural makes little sense as the it has to be split and joined in someway via post processing. 

The code in the proposed widerRepeated has this snippet:

```
  # get correct event mappings if redcap_event_name is present or not
  if ("redcap_event_name" %in% names(dat)) {
    #get the event-form mapping
    event.map <- rcon$mapping()
  } else {
    event.map = data.frame(
      unique_event_name = "",
      form = rcon$instruments()$instrument_name)
  }
  ```

I think this means that `redcap_event_name` and any other field in `rcon$mapping` is required. This is used to build the filter of rows for the `form`.

**Comment by spgarbet** [comment]
I don't see an easy way to tell if a row is related to a form, I think we can just drop anything that is `all(is.na(var.fields))`.
