### ISSUE TITLE
splitForms

### ISSUE THREAD

**Issue by spgarbet** [vubiostat/redcapAPI#126]
Need: function that given a set of Records, splits it into forms and removes NA rows. 

Design:

```
splitForms <- function(Records, rcon, envir=NULL, base="", post=NULL)
```

This function will error out if the necessary columns in Records do not exist.

Once the data for a given form is extracted, if all the non-system rows are NA or "" the row will be dropped from the final return.

The attribute(Records, "invalid") must be pulled from the passed object if it exists and filtered down to the variable names of the given form and attached to the data.frame for that form. 

It will return a list of the forms, or
  assign them to the specified environment and return an invisible(NULL)
The variable or list name will be `paste0(base, form_name)`.

The post specifies a processing function of the signature function(Records, rcon) that is called on each resulting data.frame form.

**Comment by spgarbet** [comment]
The new functions `getProjectIdFields` and `filterEmptyRow` will probably prove useful.

**Comment by nutterb** [comment]
First draft at https://github.com/vubiostat/redcapAPI/commit/d2332c7f84727f9850e75d21cb63b65d2cc13d14  Focused mostly on getting the data by forms. 

Still to be done

* assign to an environment
* remove empty rows
* restore attributes to data frame
* check that attributes to vectors are being preserved
