### ISSUE TITLE
getPass call from unlockREDCap not working on MacOS when running knitr

### ISSUE THREAD

**Issue by spgarbet** [vubiostat/redcapAPI#134]
This code block does not work when knitting on MacOS

````
---
title: "getPass test"
author: "Shawn Garbett"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(getPass)
x <- getPass::getPass("Enter Something")
```

I got `r x`!
````

This one doesn't on latest MacOS.

````
---
title: "getPass test"
author: "Shawn Garbett"
date: "`r Sys.Date()`"
output: html_document
---


```{r unlock}
library(redcapAPI)
library(Hmisc)

# Cuts down on password requests on MAC
options(keyring_backend=keyring::backend_file)

unlockREDCap(c(test_conn    = 'TestRedcapAPI'), # REDCap project 1
             keyring      = 'API_KEYs',
             envir        = globalenv(),
             url          = 'https://redcap.vanderbilt.edu/api/') 
```
````

We also tested a call from keyring to get password and that failed as well.

**Comment by spgarbet** [comment]
askpass::askpass and getPass::getPass are both broken when knitting on current MacOS / RStudio version. We just need one path to work to get this to work.

**Comment by obregos** [comment]
https://github.com/wrathematics/getPass/issues/17

**Comment by spgarbet** [comment]
I put a workaround for MacOS users in the redcap-vignette. @obregos check that out and see if it works for you. If that works we can proceed with what we have.

**Comment by spgarbet** [comment]
https://github.com/vubiostat/redcapAPI-vignette/commit/fe7fac937293611385625343f7a25d6bef6b62a9

**Comment by obregos** [comment]
Latest unlockRedcap update: [Minor bug found in working on](https://github.com/vubiostat/redcapAPI/commit/ab1c62a3f8e58c12e717896ffc58f6c3fb8651e5)  and vignette update: [Simpler Solution to RStudio+MacOS problem](https://github.com/vubiostat/redcapAPI-vignette/commit/4d74e0d2fa8fad70ab48c2428775a23a575905b5) works for me. Knits on MAC successfully

**Comment by couthcommander** [comment]
I'm not sure if it's necessary or a good idea, but I believe you could use something like this:

**Comment by spgarbet** [comment]
As ugly as that logic is, I'm giving it serious consideration. It needs to somehow be the default. Maybe an internal function `getDefaultPassFUN`?

**Comment by spgarbet** [comment]
The comprehensive suggestion from @couthcommander 

```
meth <- NA
if(requireNamespace("rstudioapi", quietly = TRUE)) {
  if(grepl('mac', tolower(utils::osVersion))) {
    inrstud <- rstudioapi::isAvailable(child_ok = TRUE)
    injob <- rstudioapi::isJob()
    if(inrstud && injob) {
      meth <- 'knitrmac'
    } else if(inrstud && !injob) {
      meth <- 'intermac'
    } else {
      meth <- 'cmdmac'
    }
  } else {
    meth <- 'nonmac'
  }
} else {
  meth <- 'norstud'
}
meth
switch(meth,
       knitrmac = rstudioapi::askForPassword(),
       intermac = rstudioapi::askForPassword(),
       getPass::getPass()
)
```

I think that's a bit much for now, but putting here in case we end up here again.
