### ISSUE TITLE
Has version 2.7.0 been released?

### ISSUE THREAD

**Issue by dmpyle** [vubiostat/redcapAPI#140]
I'm trying to export from redcap using 2.5.0 and getting errors. It looks like from your news file it looks like 2.7.0 fixes a major change in the API syntax so I assume that's the one I need. I tried updating and it still stays with 2.5.0. CRAN and rdocumentation.org also show 2.5.0 being the latest version.

rconn <- redcapAPI::redcapConnection(url = 'https://redcap.partners.org/redcap/api/', token = ***)
redcapAPI::exportRecords(rconn)
#> The call syntax of exportRecords will undergo a breaking change in the upcoming 3.0.0 release. See Issue #10
#> Error: $ operator is invalid for atomic vectors

**Comment by nutterb** [comment]
We haven't gotten it onto CRAN yet.  That will probably get published sometime this month.  (See #117 )

If you want to try 2.7.0, try running `devtools::install_github("vubiostat/redcapAPI")`

**Comment by spgarbet** [comment]
See #117.

**Comment by spgarbet** [comment]
@dmpyle would you reach out to me at my email < shawn.garbett (at) vumc.org > ?
