### ISSUE TITLE
Create body of functions for manipulating DAGs

### ISSUE THREAD

**Issue by spgarbet** [vubiostat/redcapAPI#144]
The functions to manipulate DAG need to be finished.

* `deleteDAGs`
* `deleteUsers`
* `deleteUserRoles`
* `importUsers`
* `importUserRoles`
* `importUserRoleAssignments`
* `importDAGs`
* `importDAGAssignments`

Please follow the coding style mentioned at the end of Coding Style.

Test all parameters using checkmate.

Consider how test cases can be written.

**Comment by nutterb** [comment]
exportDags is added via #171 . Tests for that function should be rewritten. The DAG that was added can be deleted as well.

**Comment by nutterb** [comment]
> Possible relevant information from another discussion:
> 
> The user "james-12345" cannot have their user privileges modified because the user belongs to a user role. Users in roles cannot have their privileges modified via the 'Import User' API method.
> 
> _The REDCap 🕺 for this one is_
> 
> 1. Retrieve and store user role on project
> 2. Clear their existing Role if they have one
> 3. Perform Import User API command
> 4. Either Re-add their previous role or programmatically assign their new one from DCRI

I'm inclined to ask that this be put into a new issue so that it can be scoped out and tested independently.  The PR I associated with this issue is already irritatingly large (sorry).

**Comment by spgarbet** [comment]
Just included as information here in case it affected anything. If it's worthy of another ticket to deal with go for it.

**Comment by nutterb** [comment]
Closed via #204

**Comment by spgarbet** [comment]
I don't truly understand all the API / DAG pieces, but I don't see the original proposed functions in the current library. Are all these functions now served via existing functions?

**Comment by nutterb** [comment]
Short answer: yes.

Long answer:

| From Initial Specification | Function Added | 
|-----------------------------|-------------------|
| deleteDAGs                       | deleteDags        |
| deleteUsers                       | deleteUsers        |
| deleteUserRoles                | deleteUserRoles |
| importUsers                      | importUsers        |
| importUserRoles               | importUserRoles | 
| importUserRoleAssignments | importUserRoleAssignments | 
| importDAGS                       | importDags        |
| importDAGAssigments       | importUserDagAssignments | 

The following were also added

* exportUserRoles
* exportUserRoleAssignments
* exportDags
* exportUserDagAssignments
* switchDag

**Comment by spgarbet** [comment]
Thanks, that makes it clearer.
