### ISSUE TITLE
Odd crash on exportRecordsTyped

### ISSUE THREAD

**Issue by spgarbet** [vubiostat/redcapAPI#146]
Exporting a really large database, a strange crash occurred.

It said that it was not provided a TRUE/FALSE and it crashed:

https://github.com/vubiostat/redcapAPI/blob/main/R/exportRecordsTyped.R#L806

**Comment by spgarbet** [comment]
```
> trimws(as.character(NULL)) == ""
logical(0)
```
I suspect this is the immediate cause. However, this would have triggered the message "No data found in the project." which is not true the project is too much data for a single transaction.

**Comment by nutterb** [comment]
ExportRecordsTyped doesn't have much in the way of handling response codes. Compare with exportRecords and the error handling piece following the API call. I won't say that we need to do it the same way as exportRecords, but I'm not sure we're processing the response codes at all.

**Comment by spgarbet** [comment]
Understood. It would be good to at least give better feedback on why it failed. I don't see anything wrong with the handling in exportRecords.

**Comment by nutterb** [comment]
This is a first stab (https://github.com/vubiostat/redcapAPI/compare/main...146-error-handling). You'll likely want me to use "null" as the default setting on `redcap_error` (instead of the option). The version of it just follows the behavior of exportRecords. 

What I could use the most help with is figuring out how to write a test for this. I'm not sure how to trigger a server error. Is there another type of error we can force to verify this works the way we want?

**Comment by nutterb** [comment]
I was knee deep in trying to figure out how to make this work when it occurred to me that `exportRecordsTyped(rcon, api_param = list(fields = "this_wont_work"))` will force an API error without having to use experimental functions. I think we'll go with this.

**Comment by spgarbet** [comment]
Nice! A functional test has better payback than a stubbed unit test.

**Comment by spgarbet** [comment]
I have a question, the `makeAPICall` is what handles retries, so when an error trickles up from that we know the retry strategy has been implemented. Correct?

**Comment by nutterb** [comment]
Yes. Retries are only made when a status code of 408, 500, 502, 503, or 504 are returned. 

Otherwise, the response code is  kicked back up to the calling function (or the last response in the case of retries)

https://github.com/vubiostat/redcapAPI/blob/main/R/makeApiCall.R#L208

**Comment by spgarbet** [comment]
PR #155
