### ISSUE TITLE
environments and the envir argument

### ISSUE THREAD

**Issue by couthcommander** [vubiostat/redcapAPI#149]
Functions with the `envir` argument often have a line like this:
```
dest <- if(is.null(envir)) list() else envir
```
(see splitForms, unlockREDCap, exportBulkRecords)

The intention is that results will be returned as a list (if NULL) or within an environment (often global). Various checks within function test if `dest` is an environment and branch:
```
if(is.environment(dest))
{
  base::assign(name, data, envir=dest)
} else
{
  dest[[name]] <- data
}
```

It would be simpler to keep `dest` a list throughout the function, and check `envir` at the very end. Currently this happens:
```
return(if(is.environment(dest)) invisible() else dest)
```

which could be replaced with this:
```
if(is.null(envir)) dest else list2env(dest, envir = envir)
```

**Comment by couthcommander** [comment]
Side note to side note - the reason `envir=1` could work is because `as.environment(1)` is another way of specifying the global environment. So if it's a number, it could be passed directly to as.environment for the proper env.

**Comment by spgarbet** [comment]
@couthcommander  See what you think of this https://github.com/vubiostat/redcapAPI/tree/issue-149-envir

Note: I found a bug in splitForms around post handling. If this looks like a good patch I will add some test cases before making a PR.

**Comment by couthcommander** [comment]
Thanks @spgarbet, that's what I had in mind.

**Comment by spgarbet** [comment]
It did reduce the code footprint a wee bit.
