### ISSUE TITLE
exportUsers forms_export shows information not provided by API

### ISSUE THREAD

**Issue by nutterb** [vubiostat/redcapAPI#156]
This may be somewhat relevant to #144 as it relates to preparing User data to be imported. 

When we use the API to export the User information, the API returns the `forms_export` column as (bold indicates data that is not provided via the user interface download).

fieldtovar_datetimes:1,randomization:1,branching_logic:1,file_import:1,calculated_fields:1,data_import_export:1,repeating_instrument:1 **,registration:1,record_id:1,text_fields:1,dates_and_times:1,numbers:1,slider_fields:1,multiple_choice:1,files_notes_descriptions:1,student_evaluation:1,teacher_evaluation:1**

I'm not sure what the bolded values are. I don't see anywhere access to field types is controlled in the UI and I'm not sure why the API is providing this information to begin with.

Some questions that come to mind:

1. Should we be retaining this information when it is received in exportUsers?
2. exportUsers has an option to expand this field to one column per form.  Do we need to provide a utility to consolidate this information into the format expected by the import method for use within importMethods?
3. If the answer to the previous question is yes, how do we want handle discrepancies between the consolidated fields and the expanded fields?

**Comment by spgarbet** [comment]
I have no idea what this information is. Should I put in a support question for clarification with the core REDCap team?

**Comment by nutterb** [comment]
I think I'd appreciate that.  I'm not certain they intended to expose it in the first place.

**Comment by spgarbet** [comment]
I sent in a request.

**Comment by spgarbet** [comment]
Reply from REDCap team: 

_those are form-level user permissions. The first part is the unique form name and the second part (the number) is the right level (seen below). Hope that helps explain that.

Form Rights: 0=No Access, 2=Read Only, 1=View records/responses and edit records (survey responses are read-only), 3=Edit survey responses_

**Comment by spgarbet** [comment]
I would say based on that we should drop them or retain to check on importRecords.

**Comment by nutterb** [comment]
Well, they didn't exactly answer the question. 

registration, record_id, text_fields, dates_and_times, etc are not forms in the project, so I'm not sure what those are supposed to tell us. But since the file downloaded through the UI doesn't include these, I'm going to go ahead and assume they weren't intended to be included in the API pull.  I'll strip them out.
