### ISSUE TITLE
metadata not parsing correctly

### ISSUE THREAD

**Issue by obregos** [vubiostat/redcapAPI#158]
```
> unlockREDCap(c(edc_conn="ACTIV6EDC"), url=url, keyring='ACTIV6EDC', envir=globalenv())
Warning message:
In scan(file = file, what = what, sep = sep, quote = quote, dec = dec,  :
  EOF within quoted string
  
```
 When viewing the metadata the form names start out correctly then at a certain variable the field annotation cuts off and the last half of the annotation becomes the next rows field_name instead. Then the rest of the rows are also completely off. My guess is that there is something in how we are grabbing form names that is not parsing correctly.
 
 example field annotation:
```
@p1000lang{"English":"<p style=\"padding-left: 40px;\">How are you today?</p> <p style=\"padding-left: 40px;\"><span style=\"font-weight: normal;\">E.g. \"I feel fantastic ....but I am tired.\"  </span></p>","Español":"<p style=\"padding-left: 40px;\">¿Cómo estás?</p> <p style=\"padding-left: 40px;\"><span style=\"font-weight: normal;\">Por ejemplo, \"Me siento fantástico, pero estoy cansado.</span></p>"}
```

The annotation cuts off after "Me siento fantástico" and the next field_name starts with "pero estoy cansado..." and the `,` is missing.

**Comment by nutterb** [comment]
I'd guess there is a high probability that there is a line break character in the field annotation.

**Comment by obregos** [comment]
Changing the annotation to the following gives me the correct metadata:
```
@p1000lang{"English":"<p style=\"padding-left: 40px;\">How are you today?</p> <p style=\"padding-left: 40px;\"><span style=\"font-weight: normal;\">E.g. \"I feel fantastic ....but I am tired."</span></p>""Español":"<p style=\"padding-left: 40px;\">¿Cómo estás?</p> <p style=\"padding-left: 40px;\"><span style=\"font-weight: normal;\">Por ejemplo \"Me siento fantástico, pero estoy cansado.</span></p>"}
```

Removing white space characters alone did not work. The issue still persisted until I deleted the comma in `Por ejemplo, \"Me siento...`.  I think the comma not parsing somehow is the issue

**Comment by spgarbet** [comment]
I got a simple failure

```
anno <- '@p1000lang{"English":"E.g. \"I inner quoted.\" ","Español":"Español Que Que"}'
x <- data.frame(stuff=1:3, fields=c("a field", anno, "c field"), more=5:6)
write.csv(x, file="~/Desktop/test.csv")
y <- read.csv("~/Desktop/test.csv")
```

**Comment by couthcommander** [comment]
That's just an error in creating your data set. This works:
```
anno <- '@p1000lang{"English":"E.g. \"I inner quoted.\" ","Español":"Español Que Que"}'
# use 4:6, not 5:6
x <- data.frame(stuff=1:3, fields=c("a field", anno, "c field"), more=4:6)
tf <- tempfile()
write.csv(x, file=tf)
y <- read.csv(tf)
```
So we still need a reproducible failure.

**Comment by obregos** [comment]
This fails for me:
`@p1000lang{"English":"<p>Blah</p> <p>Blah \"Blah\"</p>","Español":"<p>Blah</p> <p>Blah, \"Blah, Blah</p>"}`

**Comment by couthcommander** [comment]
Not for me. Maybe R version difference? I'm on 4.3.0

**Comment by obregos** [comment]
I am also on 4.3.0

**Comment by couthcommander** [comment]
```
anno <- '@p1000lang{"English":"<p>Blah</p> <p>Blah \"Blah\"</p>","Español":"<p>Blah</p> <p>Blah, \"Blah, Blah</p>"}'
x <- data.frame(stuff=1:3, fields=c("a field", anno, "c field"), more=4:6)
tf <- tempfile()
write.csv(x, file=tf)
y <- read.csv(tf)
```
See any other difference?

**Comment by spgarbet** [comment]
@obregos is running via REDCap, I was trying to isolate the problem via external code.

**Comment by obregos** [comment]
Updated the field annotation in REDCap to the correct format.
