### ISSUE TITLE
Debugging Tools Specification

### ISSUE THREAD

**Issue by spgarbet** [vubiostat/redcapAPI#161]
Recent issue #158 highlighted a need for a debug flag of some kind. 

We need to specify the debug needs and how it will be turned on/off. Here's my first draft:

* Is enabled via options. (_Yes I said that, but this is a case where it makes sense_). 
* output the formatted call to REDCap and what REDCap returns in a raw unprocessed manner.
* output text at each function call. Maybe output the data.frame dimensions or some short descriptive.

**Comment by couthcommander** [comment]
Just thinking out loud, it could be saved to global with every call similar to the way `.Last.value` works. Could possibly use an option to set verbosity (then you have two things @spgarbet hates).

**Comment by spgarbet** [comment]
I.e., all the functionality to debug the transaction already exists. I'm going to write up how to use it in the vignette.

**Comment by spgarbet** [comment]
Testing this it doesn't show the actual packet. However, I like this approach. Maybe we can just extend it and show the raw packets if requested.

**Comment by spgarbet** [comment]
I got something working and it's quite simple. @couthcommander would like your feedback, and if this is a go I'll update the vignette to reflect this.

**Comment by couthcommander** [comment]
I do think this is a decent approach. Two drawbacks I see:
 * as previously mentioned, you may want to extend this functionality. Those extensions may or may not fit into this approach as nicely.
 * printing a message is not an R object. You can capture messages but that is burdensome. The ~`.Last.value` approach gives the user an object without modifying any return values.

**Comment by spgarbet** [comment]
I think the PR just merge satisfies the goal here in a simple direct manner.
