### ISSUE TITLE
Test Framework Automation / Cleanup

### ISSUE THREAD

**Issue by spgarbet** [vubiostat/redcapAPI#169]
In working on test automation the following test framework issues have been encountered:

* The file repository artifacts / reports are not in the test database after following the vignette instructions.
* The url definition should come from the keyring so this works for other institutions.

**Comment by spgarbet** [comment]
@dupontct tells me that the API doesn't support recreating reports / files. Maybe the vignette should be changed to reference an xml export of the current project.

**Comment by nutterb** [comment]
Just added a file in the tests that will check the project for the File Repository structure needed and import it if it isn't present.

I think this makes the report the only thing that isn't fully reproducible.

**Comment by spgarbet** [comment]
Will was adding the ability to import the report ids from environment variables. I've not reviewed his last commits yet.

**Comment by obregos** [comment]
Closing issue. Resolved with #175:
  [issue-169-auto](https://github.com/vubiostat/redcapAPI/tree/issue-169-auto)
