### ISSUE TITLE
rawOrLabel='label' support for 

### ISSUE THREAD

**Issue by spgarbet** [vubiostat/redcapAPI#171]
When calling the raw API with `rawOrLabel='label'` the fields `redcap_data_access_group` and `redcap_event_name` come back as their nice internal label. It is desired to have a means of conversion for these fields. `rcon$events()` has enough information to have a cast and field map. Unfortunately `rcon$users()` does not.

**Comment by spgarbet** [comment]
Work around

```
exportBulkRecords(
  rcon,
  api_param=list(rawOrLabel='label'),
  cast=raw_cast,
  post=function(Records, conn) recastRecords(Records, conn, cast=redcapAPI:::.default_cast)
)
```

This shows we should export the default_cast list as well.

**Comment by nutterb** [comment]
Question: does the DAG export method show both the raw and labelled names? 

I actually don't know the answer to this, but might help address the issue

**Comment by spgarbet** [comment]
I haven't tried that call. Is this one on the TBD list? #144

**Comment by nutterb** [comment]
It is. I mostly wanted to leave a comment to make sure someone tried it out before hacking out way around too much.

**Comment by spgarbet** [comment]
Well the shortest path to getting the immediate report out is hacking. Longer term, I think the library needs to handle this through the export/import calls consistent with everything else. If we can call those and get the info, we can construct the proper mappings, and voila it's all part of the normal framework.

**Comment by nutterb** [comment]
Turns out, the method will provide.  The project I used doesn't have any DAGs defined, so I only got the headers, but this is what it returns. You'll notice it has columns for the name, unique name, and numeric ID.


```
> response <- 
  makeApiCall(rcon = rcon, 
              body = list(content = "dag", 
                          format = "csv", 
                          returnFormat = "csv"))

> as.character(response)
[1] "data_access_group_name,unique_group_name,data_access_group_id"
```
For an immediate solution, they might be able to leverage that into a data frame they can merge into their data.

On the other hand, it's such a simple method, when I get home this evening it would take me about an hour to put together the method and basic tests.  

Integrating with the connection object will be a little longer, especially for the offline object.

**Comment by spgarbet** [comment]
Sounds like a plan. I've asked the dev to check that call against the database with the defined entries for the DAG.

**Comment by spgarbet** [comment]
PR #172 implemented the ability to pull DAG information. Now all the information exists to create a field label mapping and provide to the cast function. What field type do we treat these as?

**Comment by nutterb** [comment]
I'm thinking if we had a field type for `dag` and `event_name` and then write `.castRecords_getCodings` to build the mappings from `rcon`, then they could respond to `castLabel` and `castRaw`

**Comment by spgarbet** [comment]
That is the design I was thinking. Why not a field type "system"? Just in case more like this come up.

**Comment by nutterb** [comment]
That's clever.  I like it.

**Comment by spgarbet** [comment]
We've got enough minor patches I think a CRAN release is in order. This is the only one I think I should hold out for a 2.7.4 release.

**Comment by spgarbet** [comment]
PR #190 Done.
