### ISSUE TITLE
Stubbed tests for `unlockREDCap`

### ISSUE THREAD

**Issue by spgarbet** [vubiostat/redcapAPI#174]
`unlockREDCap` doesn't have an automated test suite due to all manner of system dependencies. Stubbed testing is the only way to put it through the paces and specify desired behavior. This function is critical for user experience and proper testing will improve the quality of this first experience.

In addition, an expired or invalid key has a cryptic error message that needs improvement.

**Comment by spgarbet** [comment]
@obregos Please test this branch for scenarios of unlockREDCap. It's a full rewrite, and I discovered a manner to prevent repeated asking for passwords when knitting from RStudio. It will ask when running test cases. I think it's in a lot better shape, testing and specification has uncovered a lot of weird edge cases. The error messages should be a lot clearer.

**Comment by obregos** [comment]
I Knit my .Rmd file which sources my .R file containing the unlockRedcap call: 
```
unlockREDCap(
  c(eds='eds',operation='operation'),
  url='https://redcap.vanderbilt.edu/api/',
  keyring='activ6_test',
  envir=globalenv())
  ```
I was prompted for my keyring password and the report knitted successfully. Subsequent knits I did not have to enter the keyring passcode.

I did run all redcapAPI test suite cases and there were 0 failures. [ FAIL 0 | WARN 0 | SKIP 3 | PASS 1633 ]

**Comment by spgarbet** [comment]
PR #177 finished.
