### ISSUE TITLE
importRecords error with date field

### ISSUE THREAD

**Issue by jjdeclercq** [vubiostat/redcapAPI#176]
I'm trying to upload data from a .csv file using the `importRecords` function. However, when I include the date field `date_received`, I get the following error: 

`Error in as.POSIXlt.character(x, tz, ...) :
character string is not in a standard unambiguous format`

The import works upon removing the date variable. I've tried formatting the date with as.character(), as.Date() and  as.POSIXct(), as well as using the `castForImport` function. Dates are all of the format yyyy-mm-dd.

Any advice is appreciated.

```library(redcapAPI)

options(keyring_backend=keyring::backend_file) # Put in .Rprofile

redcapAPI::unlockREDCap(c(rcon = 'HIRING_test'),
             keyring     = 'hiring',
             envir       = globalenv(),
             url         = 'https://redcap.vanderbilt.edu/api/')

u1 <- read.csv("../candidate info sheets/redcap upload/Candidate Review 5.3.23_redcap_upload_2023-05-11.csv") %>%
  mutate(date_received = as.Date(date_received) )#%>% select(-date_received)

u2 <- redcapAPI::castForImport(u1, rcon)

  redcapAPI::importRecords(
    rcon = rcon,
    data = u2 %>% select(record_id, date_received),
    overwriteBehavior = "normal",
    returnContent = "auto_ids",
    force_auto_number = TRUE)```

**Comment by jjdeclercq** [comment]
Update:

I tried uploading a different date variable `date_graduate_1` and removing the offending date variable `date_received` and I was able to upload without issue.

```
u1 <- read.csv("../candidate info sheets/redcap upload/Candidate Review 5.3.23_redcap_upload_2023-05-11.csv") %>%
  mutate(date_graduate_1 = as.Date("2022-02-02")) %>% select(-date_received)
```

changing the name `u1 %<>% rename(date_graduate_1 = date_received)` also worked without issue.


The only differences between the two variables in the data dictionary is `date_received` is marked as  `@READONLY //Imported Field` in the Field Annotation column, and the Text Validation Max is designated as `today`

**Comment by nutterb** [comment]
It's the field max setting.  With it designated as `today`, the validation ends up running `as.POSIXct("today")`, which returns the error.

**Comment by jjdeclercq** [comment]
I'll ask the administrator of the redcap to remove that setting and verify that it works. Here's the traceback if it's still of any use:

```
11: stop("character string is not in a standard unambiguous format")
10: as.POSIXlt.character(x, tz, ...)
9: as.POSIXlt(x, tz, ...)
8: as.POSIXct(as.POSIXlt(x, tz, ...), tz, ...)
7: as.POSIXct.default(field_max, origin = "1970-01-01")
6: as.POSIXct(field_max, origin = "1970-01-01")
5: which(as.POSIXct(x) > as.POSIXct(field_max, origin = "1970-01-01"))
4: validate_import_date(x = data[[field_name]], field_name = field_name, 
       field_min = field_min, field_max = field_max, logfile = logfile)
3: validateImport(data = data, meta_data = MetaData, logfile = logfile)
2: importRecords.redcapApiConnection(rcon = rcon, data = u2, overwriteBehavior = "normal", 
       returnContent = "auto_ids", force_auto_number = TRUE)
1: redcapAPI::importRecords(rcon = rcon, data = u2, overwriteBehavior = "normal", 
       returnContent = "auto_ids", force_auto_number = TRUE)
```

**Comment by nutterb** [comment]
Well, don't remove that setting just yet. I can get a patch up pretty soon that will address `today` and `now`. Those particular words are easy to address. it's the piping that's thorny.

**Comment by nutterb** [comment]
I just did something similar.  For now I am using Sys.time(). It will get things up and running while we think about what we want the long term behavior to be. 

@jjdeclercq please try `devtools::install_github("vubiostat/redcapAPI", ref = "176-import-date-error")` and then try your import again.  If that works, I'll go forward with writing some tests and get a PR together within a day or two (I might have to make some changes to the test suite before submitting)

**Comment by spgarbet** [comment]
The format pre as.POSIXct is important as this keeps it in the current timezone.

**Comment by spgarbet** [comment]
Handled via PR #183.
