### ISSUE TITLE
Timeout Error Message Improvement

### ISSUE THREAD

**Issue by spgarbet** [vubiostat/redcapAPI#181]
This error was seen today from a request. Need to make sure the retry strategy deals with this case.

`<simpleError in curl::curl_fetch_memory(url, handle = handle): Recv failure: Connection reset by peer>`

**Comment by spgarbet** [comment]
This is interesting: https://stackoverflow.com/questions/38276457/error-in-curlcurl-fetch-memoryurl-handle-handle-failure-when-receiving

**Comment by spgarbet** [comment]
Maybe if the error, 

`<simpleError in curl::curl_fetch_memory(url, handle = handle): Recv failure: Connection reset by peer>`

were trapped and change it to the following:

"A network error has occurred. This can happen when too much data is requested causing a timeout, or when REDCap is having trouble servicing requests. It may also be a misconfigured proxy. 'Recv failure: Connection reset by peer'"

**Comment by nutterb** [comment]
I think this would do it: https://github.com/vubiostat/redcapAPI/compare/main...issue-181-improve-error-message

**Comment by spgarbet** [comment]
That looks fine to me. The error has multiple causes and explaining it clearer will reduce support requests.

**Comment by spgarbet** [comment]
Error (test-11-recordsTyped-exportRecordsTyped.R:4:3): records can be exported
Error in `curl::curl_fetch_memory(url, handle = handle)`: Timeout was reached: [redcap.vanderbilt.edu] SSL connection timeout

Still seeing timeouts. Just got this message. How should we handle this?

**Comment by nutterb** [comment]
This situation feels kind of whack-a-mole ish.  Though we might be able to scan status codes with error messages that might pop up to be proactive.  Otherwise I'm inclined to just add it as another message that will be caught and return our custom message:

https://github.com/vubiostat/redcapAPI/blob/main/R/redcap_error.R#L60

**Comment by spgarbet** [comment]
I'll pick this minor one up.

**Comment by spgarbet** [comment]
Nevermind, the PR's just popped up. I'll do those instead.
