### ISSUE TITLE
default timeout length

### ISSUE THREAD

**Issue by spgarbet** [vubiostat/redcapAPI#182]
For REDCap the default timeout on a request should be 5 minutes. 

There was a PR that was cancelled. https://github.com/vubiostat/redcapAPI/pull/180 

Is this the best place to change it?

**Comment by spgarbet** [comment]
There could be a name collision using c() to merge the configs.

I think we need to use the list merge with priority to the connection config, then the httr config, then have a list of default configs, which would be setting the timeout to 300.

**Comment by spgarbet** [comment]
Existing:

```
    response <-   
      httr::POST(url = rcon$url, 
                 body = c(list(token = rcon$token), 
                          body),
                 config = c(rcon$config, 
                            config))
  ```

Proposed:

```
    response <-   
      httr::POST(url = rcon$url, 
                 body = c(list(token = rcon$token), 
                          body),
                 config = modifyList(modifyList(list(httr::timeout(300), rcon$config), config)
      )
```

**Comment by spgarbet** [comment]
@nutterb Thoughts on this proposal?

**Comment by nutterb** [comment]
I think `httr` handles a lot of this for us.  Consider the following:

```
> library(redcapAPI)
> httr::set_config(httr::timeout(300))
> 
> # TIMEOUT AFTER SETTING GLOBALLY
> rcon0 <- redcapConnection(url = url, 
+                           token = API_KEY)
> resp0 <- makeApiCall(rcon0, 
+                      body = list(content = "records"))
> resp0$request$options$timeout_ms
[1] 3e+05
> 
> 
> # SETTING TIMEOUT WITHIN THE rcon
> rcon <- redcapConnection(url = url, 
+                          token = API_KEY, 
+                          config = httr::config(timeout_ms = 20000))
> resp <- makeApiCall(rcon, 
+                     body = list(content = "records"))
> resp$request$options$timeout_ms
[1] 20000
> 
> # OVERRIDE THE rcon SETTING IN THE API CALL
> resp2 <- makeApiCall(rcon, 
+                     body = list(content = "records"), 
+                     config = httr::config(timeout_ms = 10000))
> resp2$request$options$timeout_ms
[1] 10000
```

This would suggest that we can set a default timeout within `redcapConnection` by changing the `config` argument to 

`config = httr::config(timeout_ms = 3+e05)`

**Comment by nutterb** [comment]
Another approach that you will probably very much dislike is to run `httr::set_config(httr::timeout(300))` as part of the `.onLoad` function.

That might actually be the cleanest approach to set the desired default without interfering with the user's ability to make changes via the `config` arguments. 

For context, why is it that "For REDCap the default timeout on a request should be 5 minutes."  Is this an institutional thing?  is it expected by REDCap?

**Comment by spgarbet** [comment]
httr supports the config/global environment setting. I'm okay with that. The .onLoad default would be the way to go, but we'd have to make sure not to step on it already being set by the user. The config merge still needs to mergeList. 

The problem is 5 minutes is the timeout that the admin sets by default on the connections. When it gets under load that can become the expected time to satisfy a request, especially a large one. The last few days our institutions server has been under load.

**Comment by spgarbet** [comment]
The benefit of setting it in the connection config is that some user could potential set different timeouts for different connections. Why they would ever need to do that is dubious at best.

**Comment by spgarbet** [comment]
Playing with this, I see why the "c(...)" works for merge.

**Comment by nutterb** [comment]
So that means cancelling #185  and closing this issue?

**Comment by spgarbet** [comment]
I think we go forward for now. I'll be alright.
