### ISSUE TITLE
parseBranchingLogic AND / OR

### ISSUE THREAD

**Issue by spgarbet** [vubiostat/redcapAPI#186]
Using parseBranchingLogic and got this error:

 
Error in parse(text = x) : <text>:1:22: unexpected symbol

1: ((current-instance>1 AND

 Data Dictionary:

![thumbnail_image001](https://github.com/vubiostat/redcapAPI/assets/2798/713d94f4-afe8-410b-8566-aa63e0d1568e)

**Comment by nutterb** [comment]
probably ought to add `l <- tolower(l)` above line 28 (https://github.com/vubiostat/redcapAPI/blob/main/R/parseBranchingLogic.R#L28)

Be warned, even with that change, I don't think this will work. `parseBranchingLogic` wasn't written with events in mind. It will think `current-instance` is a field (two, actually; it will assume subtraction of instance from current), And even if we were able to parse that intelligently, it's hard to apply it to the data, and gets trickier when we acknowledge that we never actually know if we have all of the data relevant to understand those.

**Comment by spgarbet** [comment]
The current local code to this project is doing a "substitution / eval" approach to it. This is a complex problem, best to consider a couple thing is the current approach best and is it worth the time to solve.

I think at a minimum we update the documentation to stress the limitations. I don't know how big the user base for this is, or will be. If I can I might get the example code used to solve the problem in the project and paste here.

**Comment by spgarbet** [comment]
Also the user isn't interested in the NA values, but the values that are present and should be NA. An odd inverse of the issue.

**Comment by spgarbet** [comment]
PR #189
