### ISSUE TITLE
Logging export fails with introduction of illegal data dictionary?

### ISSUE THREAD

**Issue by berryld1** [vubiostat/redcapAPI#195]
So! I have more information on the logging export failure. Check this:

![image](https://github.com/vubiostat/redcapAPI/assets/116016336/2526806b-8848-48b2-a582-d9bd715c5005)

![image](https://github.com/vubiostat/redcapAPI/assets/116016336/594af8a5-7671-4054-9c93-c53864697eb1)

One of these absolutely behemoth datasets I'm working on cleaning - I noticed something weird, which made me dig around a bit - and long story short, I discovered one record where data had been lost because - apparently - several years ago, some field names were updated and not all the data got mapped / migrated over. (I suspect they did it by hand in Excel).

Anyhow, so I'm looking in the logging to see if this one record was just an anomaly or if there is a good bit of data to be recovered (the latter turns out to be true).

So, there were two changes of this potentially data losing type: at 2021-11-22 and at 2023-01-09.

So first I pulled the logs with end time through 2021-11-01. No problem, got the logs out without incident. Then I tried 2021-11-22 to 2023-01-09 - and I got that NA business. I kept backing it down all the way to just the one day 2021-11-22 to 2021-11-23 - NA.

So, it's like the data dictionary at 2021-11-22 introduced some illegal characters, so the logging from there cant be exported - but the logging through then can? Weird, right? Do we have a function for cleanseHistoricalMetaData? ;)

**Comment by berryld1** [comment]
And more from the logging! Of what I just did. The successful exports got the DD out - the failures did not.

![image](https://github.com/vubiostat/redcapAPI/assets/116016336/ccf25621-97ad-413b-969b-798f74e8b621)

**Comment by spgarbet** [comment]
Investigation reveals that log entries can contain (in this case they do) raw random binary data which is crashing the conversion of the csv into an R object. It would be better if it could be a graceful failure, however this may not be possible.

**Comment by spgarbet** [comment]
The core REDCap team has responded that UTF-8 is a valid response for this call.

**Comment by spgarbet** [comment]
This appears to be a corrupt log (invalid UTF-8 character) on the project and graceful handling is elusive. I don't think we can fix it.
