### ISSUE TITLE
dag argument in exportRecordsTyped is pointless

### ISSUE THREAD

**Issue by nutterb** [vubiostat/redcapAPI#196]
In a previous issue we made the decision to force all available system fields for a project into the output from `exportRecordsTyped`. This includes the `redcap_data_access_group` field.  Those reasons were legitimate and I stand by the decision. 

In writing some tests for #144 , I realized that we still have a `dag` argument in `exportRecordsTyped` that has no impact--the redcap data access groups are returned whether it is TRUE or FALSE.

I think we should evaluate if removing that argument has any impact on functionality.

**Comment by spgarbet** [comment]
Removing a flag is generally a plus in my book.

**Comment by spgarbet** [comment]
I created this patch in a branch. However, I'm not convinced this is desired. There are failing tests when this line is missing:

https://github.com/vubiostat/redcapAPI/blob/issue-196-dag-flag/R/exportRecordsTyped.R#L357

This tells me that it's having an affect.

**Comment by spgarbet** [comment]
@nutterb thoughts?

**Comment by spgarbet** [comment]
The beauty of peer review and having test cases. I'll bank this goodwill for my next brain fart. :)
