### ISSUE TITLE
exportRecordsTyped has weird interaction with field "version_confirmed"?

### ISSUE THREAD

**Issue by berryld1** [vubiostat/redcapAPI#200]
OR maybe I'm crazy?

> tmp <- exportRecordsTyped(rcon = rcon.map, fields = "record_id", cast = raw_cast)
> max(as.numeric(tmp$record_id))
[1] 330
> tmp <- exportRecordsTyped(rcon = rcon.map, fields = c("record_id", "version_confirmed"), cast = raw_cast)
> max(as.numeric(tmp$record_id))
[1] 312

Through record 312, version_confirmed = 1; from 313 to 330, version_confirmed does not have a value. 

So, if I ask for version_confirmed field, I only get records with version_confirmed == 1 ?

OR maybe I'm crazy????????

**Comment by spgarbet** [comment]
There is a filter that drops records with no values in them (outside of record_id). In this case blank has two semantic meanings and the filter treats as it as no date.

When you request just record_id the filter doesn't trigger.
When you request record_id, version_confirmed, the filter drops any row without version_confirmed having a value.

**Comment by berryld1** [comment]
Okay, I see. Is there an argument I can pass not to drop those records? Or I can just request one more field that I know will hvae values, no big deal.

**Comment by spgarbet** [comment]
Right now there isn't an argument to turn it off.

The code is like this however:

```
...
  if (identical(Raw, data.frame())){
    return(Raw)
  }
  
  Raw <- filterEmptyRow(Raw, rcon)
...
```

The raw_cast should be preventing the filter.

**Comment by spgarbet** [comment]
There isn't a flag to turn it off right now. Maybe we can add this. @nutterb I can do this quickly and turn it around. Any thoughts / objections?

**Comment by nutterb** [comment]
It seemed like a great idea when we were dealing with repeating instruments. Seems like an option to turn it off is reasonable. 

I would add it as the last argument before the dots argument.
