### ISSUE TITLE
JSON API requests

### ISSUE THREAD

**Issue by spgarbet** [vubiostat/redcapAPI#202]
The core REDCap team has suggested we switch to JSON over CSV. It's a more performant interface and supports more options on data handling. The difficulty I think this brings is that repeating instruments come back differently. Feasibility?

**Comment by spgarbet** [comment]
Further testing showed this is just random error. There is no difference in performance that I can measure.

**Comment by spgarbet** [comment]
On a large dataset it showed it took longer to import. The gains of smaller data packets are more than offset by the in-memory processing required.

The idea of using JSON would require a lot of package modification and reduce performance. For these reasons, I'm closing this request.

**Comment by obregos** [comment]
I cannot confirm that the JSON export is faster. Tested exporting about 4,348 records with the JSON-202 branch:
```
system.time(exportRecordsTyped(rcon))
   user  system elapsed
 32.237   0.709  44.624

```
```
system.time(exportRecordsTyped(rcon))
   user  system elapsed
 29.909   0.471  41.507
```

Tested exporting the same dataset from main
```
system.time(exportRecordsTyped(rcon))
   user  system elapsed 
 20.751   0.474  29.838 
```
