### ISSUE TITLE
stash data export in encrypted file

### ISSUE THREAD

**Issue by obregos** [vubiostat/redcapAPI#203]
A way to capture the data export and store it securely is desired so that users can refer to the same dataset for analysis.
The offline connection object stashes data but as plain text.
Possible "secureOffline" object may be needed. Can encryption packages in R be used?

**Comment by spgarbet** [comment]
https://github.com/talegari/safer Looks like a good package. Few dependencies, very targeted use cases. Supports symmetric and asymmetric. Do you have a design proposal for the code?

**Comment by nutterb** [comment]
Some devil's advocacy:

Is this really in scope for `redcapAPI`? While it's true the offlineConnection can hold the records, that's being held in memory. It sounds to me like the "secureOffline" object is going to be stored on disk.

Would it need to include a strong disclaimer that we do not take responsibility for loss or breach of data secured in this manner?

Nonetheless, I see the value in it. Are we sure we can implement a design that is portable across OSes and institutional environments?

I guess the big question is does it have enough benefit to outweigh the cost of development and maintenance? Or is it an internal need that would benefit from an internal package that guides your local users through institutional best practices?

My instinct for design is that the data object (at whatever state the user has it)  and the redcapConnection object ought to be saved to a file and then encrypted. Perhaps something like

```
encryptRedcapData <- function(data, rcon, file, ..., additional safer args){
  rcon$refresh_all()
  save(data, rcon, ..., file=file)
  safer::encrypt_file(file, additional safer args)
```

**Comment by spgarbet** [comment]
It's a scope question primarily. We've provided an in-memory object, the user is free to save as it wants. I lean toward outside scope of package.
