### ISSUE TITLE
Odd test failure

### ISSUE THREAD

**Issue by spgarbet** [vubiostat/redcapAPI#208]
This worked yesterday, but fails today.

```
── Failure ('test-800-exportLogging-Functionality.R:211:5'): Logs are returned for an existing Data Access Group ──
nrow(Logs) != nrow(FullLog) is not TRUE

`actual`:   FALSE
`expected`: TRUE 
```

**Comment by spgarbet** [comment]
This works upstream now. I think I got the intent right.

**Comment by nutterb** [comment]
I think your change is adequate. The logging data doesn't actually contain any information identifying the access group, so I'm not entirely sure what the output represents 

* is it logs about records in the dag?
* is it logs of actions by users in the dag?

I have a note to myself somewhere to go back and look at that, but it doesn't feel high priority.

**Comment by spgarbet** [comment]
I think somehow the logs got filled for 7 days with actions for that one DAG then the two totals were equal.
