### ISSUE TITLE
Question: Should we consider casting functions that do not cast to factors?

### ISSUE THREAD

**Issue by nutterb** [vubiostat/redcapAPI#215]
I'm weirded out by the super short list of open issues :)

I believe there still exists a certain prejudice against factors in parts of the R user base. For example (https://stackoverflow.com/questions/76815004/how-to-use-exportrecordstyped-function-from-the-redcapapi-package-to-import-the)

I think it might be reasonable to offer casting functions that cast to character vectors instead of factors. And to bundle them into a list such as `default_cast_no_factor` that would use the character castings. 

Maintenance wouldn't have to be much of an issue either.  We could write the casting functions as follows (for example)

```
castLabelCharacter <- function(x, field_name, coding){
  code_match <- getCodingIndex(x, coding)
  
  unname(coding[code_match]))
}

castLabel <- function(x, field_name, coding){
  factor(castLabelCharacter(x, field_name, coding), levels = coding, labels = names(coding))
}
```

**Comment by spgarbet** [comment]
Leaving open for additional name: `default_cast_character <- default_cast_no_factor`.

Also please update NEWS.
