### ISSUE TITLE
importRecords failing to import

### ISSUE THREAD

**Issue by obregos** [vubiostat/redcapAPI#217]
I have a field named 'weight_kg' with a validation of `text (number_1dp, Min: 22.0, Max: 225.0)`.

The following import fails with the error message below:
```
> New_Records$weight_kg <- as.numeric('22.0') 
> importRecords(destination_project, castForImport(New_Records, destination_project))
> Error in redcapError(response, error_handling = "error") : 
  400: ERROR: "1","weight_kg","22","The value you provided could not be validated because it does not follow the expected format. Please try again."
```

Changing weight_kg to character also fails with the same error above 
`New_Records$weight_kg <- as.character('22.0')`

However, setting `New_Records$weight_kg` to `as.character('22.1')` and `as.numeric('22.1')` both import successfully. There seems to be an error with accepting the .0 value as 1dp.

Tested on both redcapAPI version `2.8.0` and `2.7.4`

Ultimately, I am trying to pull data from a separate source project field with a validation of `text (number, Min: 0)`, and transform the data into the correct format to be imported to my destination project.

**Comment by nutterb** [comment]
Could you try running this before `importRecords`?

```
NewRecords <- castForImport(NewRecords, rcon, fields = "weight_kg")
```

I'm certain `castForImport` will format the value correctly.  I'm not entirely sure if `importRecords` will respond to the character value the way I'm hoping. But if it does, that's probably your easiest workaround for now.

**Comment by nutterb** [comment]
A quick scan shows that `validate_methods` doesn't have a number_1dp method, so we could probably add one to limp us along until 3.0.0 is released.

**Comment by obregos** [comment]
`New_Records <- castForImport(New_Records, destination_project, fields = "weight_kg")` does appear to return the correct format:

```
New_Records$weight_kg[1]
[1] "22.0"
class(New_Records$weight_kg[1])
[1] "character"
```

However, running the import after the assignment still gives the same error:
```
importRecords(destination_project, New_Records)
400: ERROR: "1","weight_kg","22","The value you provided could not be validated because it does not follow the expected format. Please try again."
```

**Comment by nutterb** [comment]
Nuts. I was hoping that would work. I'll cook up a validation method when I get home in a few hours.

**Comment by obregos** [comment]
Verified that the importRecords method works to correctly accept and format the values for 1 decimal place fields. Thank you!
