### ISSUE TITLE
Question: Should we validate the exportMetaData arguments `fields` and `forms`?

### ISSUE THREAD

**Issue by nutterb** [vubiostat/redcapAPI#218]
`exportMetaData` has arguments `fields` and `forms` that allow the user to only export a subset of the metadata.  Currently, these are unvalidated, and so requesting a non-existent field or form will result in an error from the API.  

Do we want to validate these against the `exportFieldNames` and `exportInstruments` before calling the API?

**Comment by spgarbet** [comment]
Unvalidated it throws an error. What is that error? If we add validation it should improve the error message.
