### ISSUE TITLE
Add methods for managing surveys

### ISSUE THREAD

**Issue by nutterb** [vubiostat/redcapAPI#221]
Methods are needed to implement the following API methods

* exportSurveyLink
* exportSurveyQueueLink
* exportSurveyReturnCode

Include tests for all three methods.

**Comment by spgarbet** [comment]
This is needed in the long run for doing a full smart variable substitution.

**Comment by spgarbet** [comment]
From the smart variable stand point there are a lot of ones that don't appear that useful, but for completeness would require this information. In our current triage of smart variables this was put in the W bucket under MoSCoW. I.e. we would do that if time allowed, lowest priority.

On the testing side, the best I think we could do is ask for the information and see if we got it.

The survey stuff is low priority, as most users are interested in just getting the data, and the 2nd biggest group is interested in modifying it .

**Comment by nutterb** [comment]
Closed via #236
