### ISSUE TITLE
Add remaining methods for project management

### ISSUE THREAD

**Issue by nutterb** [vubiostat/redcapAPI#222]
Remaining methods for project management are 

* exportProjectXML

The function should provide arguments for all existing arguments on the API documentation. Provide tests to validate arguments and functionality. 

* createProject

This may accept a data frame of initial values for the project. It should also validate that the user token is a 64 character token. 

Testing should validate the arguments, but we will be unable include automated testing for functionality as it requires a super user token that may not be available to use. Besides, it will create projects without a way to delete them, and we shouldn't be creating messes we can't clean up.

**Comment by nutterb** [comment]
Developed in https://github.com/nutterb/redcapAPI/tree/issue-222-project-management. Will wait for Issue #209 in order to implement with standardized output.

**Comment by nutterb** [comment]
Adds exportProjectXml

Adds createRedcapProject. This requires a 64 character super token. Not having one of those, I haven't actually tested if this works.  Theoretically it should, but I have no way of actually testing it. Furthermore, there's no way to delete a project via the API, so we wouldn't have a way to clean up after performing tests if we had the right token.

Would you prefer I go ahead and make the pull request, or do you want to try to organize a test on the method first?

**Comment by spgarbet** [comment]
Go ahead with the pull request.
