### ISSUE TITLE
castForImport casting 'NA' checkbox fields to '0'

### ISSUE THREAD

**Issue by obregos** [vubiostat/redcapAPI#228]
Please review the issue I am having below. Unless there is something I am doing wrong we might want to change the castForImport to not cast NA fields for checkboxes. Or is there already an argument or function I can pass into castForImport that will not cast NA fields?

Example:
I have this data frame. The 'my_variable' field is a checkbox field that is only designated for the baseline_arm_1 event
| record_id | redcap_event_name | my_variable | my_num |
|----------|----------|----------|----------|
| 1 | baseline_arm_1 | 0 | 22 |
| 2 | baseline_arm_1 | 1 | 16 |
| 1 | month_1_arm_1 | _NA_ | 30 |

When running castForImport on this data frame returns 0 for the third entry when I expected it to remain as NA:
| record_id | redcap_event_name | my_variable | my_num |
|----------|----------|----------|----------|
| 1 | baseline_arm_1 | 0 | 22 |
| 2 | baseline_arm_1 | 1 | 16 |
| 1 | month_1_arm_1 | 0 | 30 |

Importing the first data frame before the castForImport successfully imports. However, attempting to import the second data frame where NA is casted as 0 for the month_1_arm_1 event gives me the following (expected) error:
```
Error in redcapError(response, error_handling = "error") : 
  400: ERROR: "1","my_variable","0","This field ('my_variable') exists on an instrument that is not designated for the event named 'Month 1'. You are not allowed to import data for this field into this event."
```

**Comment by nutterb** [comment]
Yup. I missed a spot. Please try again.

I won't stress a lot about the class changing.  As long as the 0's, 1's and NA's line up, the import will still work.

**Comment by obregos** [comment]
Great, that works! NA is cast correctly and the import is successful. Thank you!
