### ISSUE TITLE
exportRecordsTyped 400: ERROR: The following values in the parameter "fields" are not valid

### ISSUE THREAD

**Issue by spgarbet** [vubiostat/redcapAPI#231]
I'm putting this into the issue system so it can be searched for posterity. Possibly consider adding to our vignette.

Users have been reporting a "400: ERROR: The following values in the parameter "fields" are not valid:" error when using `exportRecordsTyped`. The field that it reports does not exist in the project.

It can be caused by "secondary id" being enabled. This is under 'Project Setup > Enable optional modules and customizations > Additional Customizations >   Designate a Secondary Unique Field'. What has happened in projects is this is turned on, then the field_name gets changed but it remains in the setup with the old name. A lot of logic in this library goes into figuring out exactly what fields to request, if this is enabled it's used as an identifier that's requested on a call. If this field no longer exists then this error pops up.

To fix: disable 'Secondary Unique Field'. Run `rcon$flush_all()` (if rcon is your connection object) to clear any cached values. Then retry the exportRecordsTyped. 

In one instance, the field could not be cleared via the REDCap interface and the core team had to take care of it.

**Comment by nutterb** [comment]
Maybe add an extra check here (https://github.com/vubiostat/redcapAPI/blob/main/R/getProjectIdFields.R#L22C77-L27) that only adds the secondary identifier if the field specified as the identifier exists in the meta data?

**Comment by spgarbet** [comment]
That is an interesting idea. The code might be able to successfully ignore the problem.

**Comment by nutterb** [comment]
> That is an interesting idea. The code might be able to successfully ignore the problem. Should still throw a warning in this case.

I think the warning is a good idea. I was surprised at how easy it was to stumble into this. 

I thought it was interesting that after changing the secondary field name, the web UI automatically disabled the secondary field functionality, but didn't actually clear the field in the database.
