### ISSUE TITLE
drop redcapFactor usage on export methods

### ISSUE THREAD

**Issue by spgarbet** [vubiostat/redcapAPI#25]
Users are reporting that they strip redcapFactor from output columns. 

Consider all export methods.

Question: does redcapFactor offer any benefit to the end user? If not can we just strip it altogether?

Internal ref: BSTATGEN-1096

Currently used code:

```
if(rmrcl)
    for(v in n) {
      x <- d[[v]]
      if(inherits(x, 'redcapFactor')) {
        class(x) <- setdiff(class(x), 'redcapFactor')
        attr(x, 'redcapLabels') <- attr(x, 'redcapLevels') <- NULL
        d[, (v) := x]
        }
    } 
```

**Comment by nutterb** [comment]
There _can_ a benefit to the end user. The most likely use case I can think of is a quality of life survey (perhaps the SF36?) where the responses have a numerical value. You lose access to those values when R creates a factor (which is always an integer from 1 to n with associated labels).

That being said, I think dropping this feature probably makes sense. I recall having some problems with downstream work because of the attributes, many of which will get tossed by the more common data processing tools anyway. 

If a user needs to convert a factor to it's underlying coding, we should be able to do that through the meta data instead.

**Comment by spgarbet** [comment]
```
> x <- factor(sample(c(3, 5, 6),10,replace=TRUE))
> x
 [1] 3 6 5 5 6 5 6 6 3 3
Levels: 3 5 6
> as.numeric(x)
 [1] 1 3 2 2 3 2 3 3 1 1
> as.numeric(as.character(x))
 [1] 3 6 5 5 6 5 6 6 3 3
```
I see your point. The original code map can be lost. Let's say it's "1=Yes, 2=No and 99=Unable to Contact". Conversion to an R factor loses that original mapping. redcapFactor is means to preserve that original map. 

Looking at the relevant code however, redcapFactor doesn't respect factors=FALSE. This doesn't seem like desired behavior. 

https://github.com/vubiostat/redcapAPI/blob/ddc3d44a678889e91b718f9746e2ee3ef09813a9/R/makeRedcapFactor.R#L51-L53

Proposal: (1) Respect the factors flag and not create redcapFactor class extensions if it's false. (2) Only make something a redcapFactor if it preserves additional information about the mapping.

**Comment by nutterb** [comment]
I question if we can easily decipher what qualifies as "preserves additional information." 

Stepping back and looking at the big picture, redcapFactor feels like it was a solution to a very rare problem. And then that solution got thrown at everything that wasn't the problem. I'm still inclined toward dropping the class entirely and putting together a `switchCoding` function that can remap a single variable and translate it from label to code (or vice versa). 

If that isn't appealing, I'd say proposal 1) is good, but I'd be inclined to continue using redcapFactor when factors = TRUE and focus on cleaning up behavior of the class

I could be wrong, but I'd guess that a lot of the dislike of redcapFactor is that it is messy and clunky. Just printing it creates a disaster on the screen. 

```
> yn <- redcapAPI:::makeRedcapYN(c(0, 1), FALSE)
> 
> # print it
> yn
[1] 0 1
Levels: 
Warning message:
In print.factor(x) : factor levels must be "character"
> 
> # print it after a function
> sqrt(yn)
[1] 0 1
Levels: 
Warning message:
In print.factor(x) : factor levels must be "character"
> 
> #extraction
> yn[1]
[1] 0
attr(,"redcapLabels")
[1] "No"  "Yes"
attr(,"redcapLevels")
[1] 0 1
```

**Comment by spgarbet** [comment]
Frank had this suggestion: One option to think about for the future is prepending the original codes and colon in front of the R value labels (factor levels) or to have an option to do that.

Current proposal is: (1) drop redcapFactor entirely. (2) Add option to append original code with a colon.

**Comment by nutterb** [comment]
While working on #29 I found it prudent to write a function that provided the mapping (I had deconstructed the field choices in three different places). It might be of use for providing the mapping.

https://github.com/nutterb/redcapAPI/blob/Issue29-stringr/R/fieldChoiceMapping.R

**Comment by spgarbet** [comment]
See `exportRecordsTyped` for the fix.
