### ISSUE TITLE
Convience Functions for offline work. 

### ISSUE THREAD

**Issue by spgarbet** [vubiostat/redcapAPI#255]
Use Case: Analyst wishes to download everything from a REDCap project to share with others and work offline. 

Design:

1. extend `preserveProject` to have the option of writing the data frames to a CSVs, via a `directory` option. 
2. If this option is enabled, return a list of file locations (or the directory) instead of the list of data frames
3. Add a `offlineConnectionFromList`, or maybe an `offlineConnection.list` method that takes the output from `preserveProject` and forms the offline connection object.

**Comment by nutterb** [comment]
Closed via #263
