### ISSUE TITLE
How to turn off fancy formatting of `redcap_event_name` and `redcap_repeat_instrument` when using `exportRecordsTyped`?

### ISSUE THREAD

**Issue by thomasgstewart** [vubiostat/redcapAPI#257]
Hi Shawn and Benjamin and team-

I noticed that `exportRecordsTyped` now formats the values in `redcap_event_name` variables.  For example, what used to be `screening_arm_1` is now `Screening (Arm 1: Arm 1)`, which is nice change.  However, I'm in a situation where downstream processing of the data needs to work whether the data was pulled from Redcap as an export or as an API call.  Is there a switch to flip so that API data, particularly for variables like `redcap_event_name`, returns the same values as a direct export?

Apologies, if this is addressed somewhere, and I missed it.

**Comment by nutterb** [comment]
Try adding `cast = list(system = castRaw)`

I believe this is documented in `?exportRecordsTyped`, but if you think there is a more natural way to help you find this information, please let us know.

**Comment by nutterb** [comment]
I should look at code before I open my mouth. I don't see this documented in either exportRecordsTyped of fieldValidationAndCasting.

Let's leave this open and find the right place to put it.

**Comment by spgarbet** [comment]
I would take a more targeted approach but I'm having trouble figuring out what the field name for events are. Is it system. Assuming that it is a system field type this would be better:

`exportRecordsTyped(rcon, cast=list(system=castRaw))`
