### ISSUE TITLE
exportRecordsTyped 400: ERROR: The following values in the parameter "fields" are not valid: 'specimen_study_id'

### ISSUE THREAD

**Issue by jresser04** [vubiostat/redcapAPI#267]
Hi there,

I am encountering an error when running `exportRecordsTyped` on a REDCap connection object:

view.ar <- exportRecordsTyped(view_conn)
Error in redcap_error(response, error_handling = error_handling) : 
  400: ERROR: The following values in the parameter "fields" are not valid: 'specimen_study_id'

`specimen_study_id` is NOT a field in this REDCap database. 

There is an existing related issue: (https://github.com/vubiostat/redcapAPI/issues/231 ), but I am still receiving the error rather than a warning.

**Comment by spgarbet** [comment]
The queries are constructed from the fields reported in the meta data. Can you look at the project's metadata and see if `specimen_study_id` is being reported somewhere?

```
meta <- view_conn$metadata()
View(meta)
```

**Comment by nutterb** [comment]
Could you also run `packageVersion("redcapAPI")` and let us know which version you are using?

**Comment by jresser04** [comment]
Here is what meta looks like. `specimen_study_id` not listed.

        field_name                     form_name section_header field_type      field_label
 specimen_barcode analysis_ready_results_upload             NA       text Specimen Barcode
      result_type analysis_ready_results_upload             NA       text      Result Type
           result analysis_ready_results_upload             NA       text           Result
      comment_box analysis_ready_results_upload             NA      notes         Comments

I am running version 2.7.4.

**Comment by jresser04** [comment]
I just updated to version 2.8.0 and now getting a warning rather than the error. Data import fine aside from the warning. Package version was probably the culprit here.

view.ar <- exportRecordsTyped(view_conn)
Warning messages:
1: In getProjectIdFields(rcon) :
  Project information specifies a secondary unique field that does not exist.
2: In getProjectIdFields(rcon) :
  Project information specifies a secondary unique field that does not exist.

**Comment by nutterb** [comment]
I was hoping an update would be all you needed. Glad to see it's working for you.

**Comment by jresser04** [comment]
[like]  Resser, John Jackson reacted to your message:
________________________________

**Comment by spgarbet** [comment]
So it was #231 after all. @jresser04, the project has some misconfiguration around the secondary id field. Secondly, if this is going to target the BRS server we will need to start the upgrade process for the package on BRS to roll your report.

**Comment by jresser04** [comment]
I haven't yet used `redcapAPI` to load data for reports on BRS. I am planning to in the future though, so we will want to upgrade the package on BRS at some point.

**Comment by spgarbet** [comment]
Just found out the updated roll is in progress. @nutterb We're probably due for 2.8.2 on any further tweaks.

**Comment by nutterb** [comment]
I don't understand what you mean by "updated roll is in progress."  But I can say that I have no interesting tweaks in development. (I'm tinkering with some long-form documentation for casting, but I wouldn't delay a release for that)

**Comment by spgarbet** [comment]
We have some production servers that run reports on a crontab. Updating the redcapAPI package means we go through a regresssion and test all the existing reports. 2.8.1 has some really nice bug fixes that folks are already appreciating. Now that 2.8.1 is in process of going to a production server (BRS: Biostats Reporting Server), it makes it easier for me to track things if we move to 2.8.2.
