### ISSUE TITLE
Codebook style listing of multiple choice variables

### ISSUE THREAD

**Issue by nutterb** [vubiostat/redcapAPI#268]
> Hi.  Have you seen this API?  https://epicentre-msf.github.io/redcap/reference/meta_factors.html   This functionality in the redcapAPI would be quite useful.  Currently, users have to manually parse out the data dictionary to do this.  I've noticed that my code no longer works the same with 2.8.0 and my factor labels are incorrectly aligned with the actual data values.  I'd normally just say, "Well, another day, another R package" but this one is only on github, so I can't see asking users to install and use in case it disappears...

_Originally posted by @SimpleAddress4390 in https://github.com/vubiostat/redcapAPI/issues/246#issuecomment-1786428469_

**Comment by nutterb** [comment]
I'm not familiar with this package. I may explore it to see what useful features it inspires. 

It looks like `meta_factors` is producing something similar to the REDCap codebook for radio, dropdown, checkbox, and yesno values. The closest `redcapAPI` has for that is `fieldChoiceMapping`, which returns a matrix of the mappings for radio, dropdown, and checkbox fields. (yesno are always 0/1 coded fields). 

```
> fieldChoiceMapping(rcon, "dropdown_test")
     choice_value choice_label
[1,] "1"          "Green"     
[2,] "2"          "Blue"      
[3,] "3"          "Lavender"  
> fieldChoiceMapping(rcon, "radio_test")
     choice_value choice_label
[1,] "a"          "Carnation" 
[2,] "b"          "Tulip"     
[3,] "c"          "Daffodil"  
> fieldChoiceMapping(rcon, "checkbox_test")
     choice_value choice_label
[1,] "x"          "Guitar"    
[2,] "y"          "Ukulele"   
[3,] "z"          "Mandolin"  
```

Questions I would ask before developing something like this (these questions are not intended to be discouraging of the idea. Rather, I'd like to understand to motivations so anything that gets developed actually addresses the proper need):

1. How do/would you use this feature?  
2. What problem does it solve (or what convenience does it add)? 
3. Is this part of your data exploration? or is it something you display to your clients?
4. How often do you use/need such a feature?
5. What is your fallback if this feature is unavailable?
6. What would your desired output be?  Would you add/remove anything from the content in `meta_factors`?

@spgarbet , are there any whisperings from your user base that might be addressed by something like this?

**Comment by SimpleAddress4390** [comment]
Thanks.  I will look at that function as well.

as for your questions:  (Please do not laugh at me)


   1. How do/would you use this feature?
   Again, don't laugh.  I use the redcapAPI to extract a study's data from
   REDCap, process it, turn it into SAS files, document the heck out of it
   all, further process it, then save it out as SAS and R files for analysts.
   [I'm kinda chuckling myself as I read this]

   To create good SAS datasets, i need to create SAS formats that allow
   users to see the 'raw' (0/1/2/3/etc.) values and the 'coded' values
   (yes/no/maybe, etc.)  I also need to put SAS labels on datasets.

   2. What problem does it solve (or what convenience does it add)?
   The present method I coded is 100 lines of nonsense to accomplish what
   the meta_factors function does directly.  If nothing else, it creates more
   structured metadata from the REDCap system.

   3. Is this part of your data exploration? or is it something you display
   to your clients?
   It is metadata used for preparing data for analysis.  I currently create
   a 'data dictionary' from the REDCap metadata, and a 'factors dictionary'
   which describes the connection between a variable's actual value and the
   'factor' labels.

   4. How often do you use/need such a feature?
   I would use it with every extraction.

   5. What is your fallback if this feature is unavailable?
   Now that I see the example from this person's API, I might try to code a
   duplicate instead of my present process of trying to do this from the
   attributes of the factor dataframes.

   6. What would your desired output be? Would you add/remove anything from
   the content in meta_factors?
   To me it is fine as a dataframe in the current structure.  It can always
   be merged with other info if it has the form/field info.

**Comment by nutterb** [comment]
If I'm laughing it's only because I've done numerous chuckle-worthy things of this sort myself. 

Proposal

```
assembleCodebook(rcon, 
                 fields = NULL, 
                 forms = NULL, 
                 drop_fields = NULL, # Same as drop_fields in exportRecordsTyped
                 field_types = NULL, 
                 include_form_complete = TRUE,
                 expand_check = FALSE)
```

Fields included in the code book will be the intersection of fields found between `fields` and `forms`. Any fields listed in `drop_fields` will be excluded. If specified, only fields in `field_types` will be included.

**Output for multiple choice with `expand_check = FALSE`**

| field_name | form | field_type | value | label | min | max | branching_logic | 
|-------------|------|-------------|-------|-------|-----|------|-------------------|
| dropdown | form name | dropdown | 0 | label 0 | NA | NA | ... |
| dropdown | form name | dropdown | 1 | label 1 | NA | NA | ... |
| radio         | form name | radio         | a | label A |  NA | NA | ... |
| radio         | form name | radio         | b | label B |  NA | NA | ... |
| checkbox | form name | checkbox | x | label X |  NA | NA | ... |
| checkbox | form name | checkbox | y | label Y |  NA | NA | ... |
| checkbox | form name | checkbox | z | label Z |  NA | NA | ... |
| yesno      | form name  | yesno      | 0 | No |  NA | NA | ... |
| yesno      | form name | yesno       | 1 | Yes |  NA | NA | ... |
| truefalse | form name | truefalse | 0 | FALSE |  NA | NA | ... |
| truefalse | form name | truefalse | 1 | TRUE |  NA | NA | ... |
| form_complete | form name | formcomplete | 0 | Incomplete | NA | NA |  ... |
| form_complete | form name | formcomplete | 1 | Unverified | NA | NA |  ... |
| form_complete | form name | formcomplete | 2 | Complete | NA | NA |  ... |


**Output for multiple choice with `expand_check = TRUE`**

| field_name | form | field_type | value | label | Min | Max |  branching_logic | 
|-------------|------|-------------|-------|-------|-----|------|------|
| checkbox___x | form name | checkbox | 0 | Unchecked |  NA | NA | ... |
| checkbox___x | form name | checkbox | 1 | Checked |  NA | NA | ... |
| checkbox___y | form name | checkbox | 0 | Unchecked |  NA | NA | ... |
| checkbox___y | form name | checkbox | 1 | Checked |  NA | NA | ... |
| checkbox___z | form name | checkbox | 0 | Unchecked |  NA | NA | ... |
| checkbox___z | form name | checkbox | 1 | Checked |  NA | NA | ... |

**Output for non-multiple choice (Examples)**

| field_name | form | field_type | value | label | Min | Max |  branching_logic | 
|-------------|------|-------------|-------|-------|-----|------|------|
| number  | form name | number | NA | NA | min | max |  ... |
| date  | form name | date | NA | NA | min | max |  ... |
| datetime  | form name | datetime | NA | NA | min | max |  ... |
| slider  | form name | slider | NA | NA | min | max |  ... |
| text  | form name | text | NA | NA | NA | NA |  ... |
| calc  | form name | calc | NA | NA | NA | NA |  ... |

**Comment by spgarbet** [comment]
We usually go the other direction, from SAS into R. However, there are plenty of SAS users out there that would benefit from this.

**Comment by couthcommander** [comment]
Somewhat along these lines - REDCap provides an R script for users that download data from the web site (non API users). It creates factors, sets labels, etc. Having this `assembleCodebook` functionality could allow you to replicate this script provided by REDCap. On its surface, I'm not sure that this would actually offer anything useful (though perhaps comforting if the scripts match). But I could see scenarios where users want common transformations to occur (including casting), where it would be beneficial for the code to be saved to script. One big scenario this could cover would be converting to SAS (we need this functionality!).

I've done a little bit of work on creating a data dictionary from REDCap's R script -- [see rcmoonpie](https://github.com/couthcommander/rcmoonpie/blob/main/vignette.pdf). Using API meta data is much more straight-forward. Feel free to borrow any code/ideas, though I expect it's not needed here.

**Comment by nutterb** [comment]
@SimpleAddress4390 , @couthcommander 

from `devtools::install_github("vubiostat/redcapAPI", ref = "issue-268-assembleCodebook")`, I can run the following and produce the table below.  Does this move you toward your goals? (I see now my form order is not what I intended, but it's late. I'll get that tomorrow)

```
assembleCodebook(rcon)

# Note: printed as a tbl_df solely for convenience of display
# A tibble: 119 x 10
    field_name                        form_name              field_type value label min     max branching_logic field_order form_order
    <chr>                             <chr>                  <chr>      <chr> <chr> <lgl> <int> <chr>                 <int>      <dbl>
  1 record_id                         record_id              text       NA    NA    NA       NA NA                        1          1
  2 treatment                         randomization          dropdown   1     Cont~ NA       NA NA                        2          2
  3 treatment                         randomization          dropdown   2     Trea~ NA       NA NA                        2          2
  4 email_test                        text_fields            email      NA    NA    NA       NA NA                        3          3
  5 letters_only_test                 text_fields            alpha_only NA    NA    NA       NA NA                        4          3
  6 phone_test                        text_fields            phone      NA    NA    NA       NA NA                        5          3
  7 text_test                         text_fields            text       NA    NA    NA       NA NA                        6          3
  8 bioportal_test                    text_fields            bioportal  NA    NA    NA       NA NA                        7          3
  9 zipcode_test                      text_fields            zipcode    NA    NA    NA       NA NA                        8          3
 10 date_mdy_test                     dates_and_times        date_      NA    NA    NA       NA NA                        9          4
 11 date_ymd_test                     dates_and_times        date_      NA    NA    NA       NA NA                       10          4
 12 datetime_dmy_hm_test              dates_and_times        datetime_  NA    NA    NA       NA NA                       11          4
 13 datetime_mdy_hm_test              dates_and_times        datetime_  NA    NA    NA       NA NA                       12          4
 14 datetime_ymd_hm_test              dates_and_times        datetime_  NA    NA    NA       NA NA                       13          4
 15 datetime_dmy_hms_test             dates_and_times        datetime_~ NA    NA    NA       NA NA                       14          4
 16 datetime_mdy_hms_test             dates_and_times        datetime_~ NA    NA    NA       NA NA                       15          4
 17 datetime_ymd_hms_test             dates_and_times        datetime_~ NA    NA    NA       NA NA                       16          4
 18 time_hhmm_test                    dates_and_times        time       NA    NA    NA       NA NA                       17          4
 19 time_mmss_test                    dates_and_times        time_mm_ss NA    NA    NA       NA NA                       18          4
 20 date_dmy_test                     dates_and_times        date_      NA    NA    NA       NA NA                       19          4
 21 integer_test                      numbers                integer    NA    NA    NA       NA NA                       20          5
 22 number_1dp_comma_test             numbers                number_1d~ NA    NA    NA       NA NA                       21          5
 23 number_1dp_test                   numbers                number_1dp NA    NA    NA       NA NA                       22          5
 24 number_2dp_comma_test             numbers                number_2d~ NA    NA    NA       NA NA                       23          5
 25 number_2dp_test                   numbers                number_2dp NA    NA    NA       NA NA                       24          5
 26 number_test                       numbers                number     NA    NA    NA       NA NA                       25          5
 27 slider_no_label_test              slider_fields          slider     NA    NA    NA       50 NA                       26          6
 28 slider_show_number_test           slider_fields          slider     NA    NA    NA       NA NA                       27          6
 29 slider_text_label_test            slider_fields          slider     NA    NA    NA       NA NA                       28          6
 30 checkbox_test                     multiple_choice        checkbox   x     Guit~ NA       NA NA                       29          7
 31 checkbox_test                     multiple_choice        checkbox   y     Ukul~ NA       NA NA                       29          7
 32 checkbox_test                     multiple_choice        checkbox   z     Mand~ NA       NA NA                       29          7
 33 dropdown_test                     multiple_choice        dropdown   1     Green NA       NA NA                       30          7
 34 dropdown_test                     multiple_choice        dropdown   2     Blue  NA       NA NA                       30          7
 35 dropdown_test                     multiple_choice        dropdown   3     Lave~ NA       NA NA                       30          7
 36 radio_test                        multiple_choice        radio      a     Carn~ NA       NA NA                       31          7
 37 radio_test                        multiple_choice        radio      b     Tulip NA       NA NA                       31          7
 38 radio_test                        multiple_choice        radio      c     Daff~ NA       NA NA                       31          7
 39 truefalse_test                    multiple_choice        truefalse  0     FALSE NA       NA NA                       32          7
 40 truefalse_test                    multiple_choice        truefalse  1     TRUE  NA       NA NA                       32          7
 41 yesno_test                        multiple_choice        yesno      0     No    NA       NA NA                       33          7
 42 yesno_test                        multiple_choice        yesno      1     Yes   NA       NA NA                       33          7
 43 descriptive_test                  files_notes_descripti~ descripti~ NA    NA    NA       NA NA                       34          8
 44 file_upload_test                  files_notes_descripti~ file       NA    NA    NA       NA NA                       35          8
 45 notes_test                        files_notes_descripti~ notes      NA    NA    NA       NA NA                       36          8
 46 signature_test                    files_notes_descripti~ file       NA    NA    NA       NA NA                       37          8
 47 left_operand                      calculated_fields      number     NA    NA    NA       NA NA                       38          9
 48 right_operand                     calculated_fields      number     NA    NA    NA       NA NA                       39          9
 49 calc_addition                     calculated_fields      calc       NA    NA    NA       NA NA                       40          9
 50 calc_squared                      calculated_fields      calc       NA    NA    NA       NA NA                       41          9
 51 row_purpose                       branching_logic        notes      NA    NA    NA       NA NA                       42         10
 52 prereq_radio                      branching_logic        radio      1     Radi~ NA       NA NA                       43         10
 53 prereq_radio                      branching_logic        radio      2     Radi~ NA       NA NA                       43         10
 54 prereq_radio                      branching_logic        radio      ABC   Radi~ NA       NA NA                       43         10
 55 prereq_radio                      branching_logic        radio      4     Do n~ NA       NA NA                       43         10
 56 prereq_checkbox                   branching_logic        checkbox   1     Chec~ NA       NA NA                       44         10
 57 prereq_checkbox                   branching_logic        checkbox   2     Chec~ NA       NA NA                       44         10
 58 prereq_checkbox                   branching_logic        checkbox   ABC   Chec~ NA       NA NA                       44         10
 59 prereq_checkbox                   branching_logic        checkbox   4     Do n~ NA       NA NA                       44         10
 60 prereq_number                     branching_logic        number     NA    NA    NA       NA NA                       45         10
 61 prereq_date                       branching_logic        date_      NA    NA    NA       NA NA                       46         10
 62 prereq_yesno                      branching_logic        yesno      0     No    NA       NA NA                       47         10
 63 prereq_yesno                      branching_logic        yesno      1     Yes   NA       NA NA                       47         10
 64 no_prereq_number                  branching_logic        number     NA    NA    NA       NA NA                       48         10
 65 no_prereq_checkbox                branching_logic        checkbox   1     Pret~ NA       NA NA                       49         10
 66 no_prereq_checkbox                branching_logic        checkbox   2     Choc~ NA       NA NA                       49         10
 67 no_prereq_checkbox                branching_logic        checkbox   3     Fruit NA       NA NA                       49         10
 68 one_prereq_non_checkbox           branching_logic        dropdown   1     Book  NA       NA [prereq_radio]~          50         10
 69 one_prereq_non_checkbox           branching_logic        dropdown   2     Conc~ NA       NA [prereq_radio]~          50         10
 70 one_prereq_non_checkbox           branching_logic        dropdown   3     Movie NA       NA [prereq_radio]~          50         10
 71 one_prereq_checkbox               branching_logic        date_      NA    NA    NA       NA [prereq_checkb~          51         10
 72 two_prereq_and                    branching_logic        radio      1     blue  NA       NA [prereq_yesno]~          52         10
 73 two_prereq_and                    branching_logic        radio      2     purp~ NA       NA [prereq_yesno]~          52         10
 74 two_prereq_and                    branching_logic        radio      3     red   NA       NA [prereq_yesno]~          52         10
 75 two_prereq_or                     branching_logic        truefalse  0     FALSE NA       NA [prereq_yesno]~          53         10
 76 two_prereq_or                     branching_logic        truefalse  1     TRUE  NA       NA [prereq_yesno]~          53         10
 77 two_prereq_and_one_check          branching_logic        text       NA    NA    NA       NA [prereq_checkb~          54         10
 78 three_prereq_andor                branching_logic        dropdown   1     Chri~ NA       NA ([prereq_radio~          55         10
 79 three_prereq_andor                branching_logic        dropdown   2     Davi~ NA       NA ([prereq_radio~          55         10
 80 three_prereq_andor                branching_logic        dropdown   3     Matt~ NA       NA ([prereq_radio~          55         10
 81 three_prereq_andor                branching_logic        dropdown   4     Pete~ NA       NA ([prereq_radio~          55         10
 82 three_prereq_andor                branching_logic        dropdown   5     Jodi~ NA       NA ([prereq_radio~          55         10
 83 one_prereq_inequality             branching_logic        yesno      0     No    NA       NA [prereq_number~          56         10
 84 one_prereq_inequality             branching_logic        yesno      1     Yes   NA       NA [prereq_number~          56         10
 85 repeat_question_1                 repeating_instrument   text       NA    NA    NA       NA NA                       57         11
 86 repeat_datetime                   repeating_instrument   datetime_  NA    NA    NA       NA NA                       58         11
 87 multiple_choice_complete          NA                     form_comp~ 0     Inco~ NA       NA NA                       59         NA
 88 multiple_choice_complete          NA                     form_comp~ 1     Unve~ NA       NA NA                       59         NA
 89 multiple_choice_complete          NA                     form_comp~ 2     Comp~ NA       NA NA                       59         NA
 90 record_id_complete                NA                     form_comp~ 0     Inco~ NA       NA NA                       60         NA
 91 record_id_complete                NA                     form_comp~ 1     Unve~ NA       NA NA                       60         NA
 92 record_id_complete                NA                     form_comp~ 2     Comp~ NA       NA NA                       60         NA
 93 files_notes_descriptions_complete NA                     form_comp~ 0     Inco~ NA       NA NA                       61         NA
 94 files_notes_descriptions_complete NA                     form_comp~ 1     Unve~ NA       NA NA                       61         NA
 95 files_notes_descriptions_complete NA                     form_comp~ 2     Comp~ NA       NA NA                       61         NA
 96 randomization_complete            NA                     form_comp~ 0     Inco~ NA       NA NA                       62         NA
 97 randomization_complete            NA                     form_comp~ 1     Unve~ NA       NA NA                       62         NA
 98 randomization_complete            NA                     form_comp~ 2     Comp~ NA       NA NA                       62         NA
 99 numbers_complete                  NA                     form_comp~ 0     Inco~ NA       NA NA                       63         NA
100 numbers_complete                  NA                     form_comp~ 1     Unve~ NA       NA NA                       63         NA
101 numbers_complete                  NA                     form_comp~ 2     Comp~ NA       NA NA                       63         NA
102 dates_and_times_complete          NA                     form_comp~ 0     Inco~ NA       NA NA                       64         NA
103 dates_and_times_complete          NA                     form_comp~ 1     Unve~ NA       NA NA                       64         NA
104 dates_and_times_complete          NA                     form_comp~ 2     Comp~ NA       NA NA                       64         NA
105 text_fields_complete              NA                     form_comp~ 0     Inco~ NA       NA NA                       65         NA
106 text_fields_complete              NA                     form_comp~ 1     Unve~ NA       NA NA                       65         NA
107 text_fields_complete              NA                     form_comp~ 2     Comp~ NA       NA NA                       65         NA
108 slider_fields_complete            NA                     form_comp~ 0     Inco~ NA       NA NA                       66         NA
109 slider_fields_complete            NA                     form_comp~ 1     Unve~ NA       NA NA                       66         NA
110 slider_fields_complete            NA                     form_comp~ 2     Comp~ NA       NA NA                       66         NA
111 calculated_fields_complete        NA                     form_comp~ 0     Inco~ NA       NA NA                       67         NA
112 calculated_fields_complete        NA                     form_comp~ 1     Unve~ NA       NA NA                       67         NA
113 calculated_fields_complete        NA                     form_comp~ 2     Comp~ NA       NA NA                       67         NA
114 repeating_instrument_complete     NA                     form_comp~ 0     Inco~ NA       NA NA                       68         NA
115 repeating_instrument_complete     NA                     form_comp~ 1     Unve~ NA       NA NA                       68         NA
116 repeating_instrument_complete     NA                     form_comp~ 2     Comp~ NA       NA NA                       68         NA
117 branching_logic_complete          NA                     form_comp~ 0     Inco~ NA       NA NA                       69         NA
118 branching_logic_complete          NA                     form_comp~ 1     Unve~ NA       NA NA                       69         NA
119 branching_logic_complete          NA                     form_comp~ 2     Comp~ NA       NA NA                       69         NA
```

**Comment by nutterb** [comment]
> I could see scenarios where users want common transformations to occur (including casting), where it would be beneficial for the code to be saved to script. One big scenario this could cover would be converting to SAS (we need this functionality!).

With regards to the R script, how strong of a need do you think there is to be able to generate a script from the data dictionary? I'd like to think scripts are being saved by users that are using the API directly. And with the efforts we've put into offline connections, I don't think there is much difference between a script with an API connection and a script with an offline connection. 

But I have to admit, I'm not familiar with the workflows that might want something different.

With regards to generating SAS scripts....I haven't touched SAS in over a decade.  You guys will have to take that one up on your own. :)

> I've done a little bit of work on creating a data dictionary from REDCap's R script -- [see rcmoonpie]

How much do you want the YAML form of the data dictionary?  With what I've put together already, it shouldn't be hard to produce, but I'd like to make sure there's a market for such a product.

**Comment by couthcommander** [comment]
> With regards to the R script, how strong of a need do you think there is to be able to generate a script from the data dictionary? I'd like to think scripts are being saved by users that are using the API directly. And with the efforts we've put into offline connections, I don't think there is much difference between a script with an API connection and a script with an offline connection.

In general, I think this is very low priority. The scenario I had in my head was that you have two users - one that uses the API and one that does not. The API user writes their code and redcapAPI generates a perfect data set. The non-API user downloads a data set from REDCap but doesn't have a perfect data set. If the package generated an R script, it could be shared to the non-API user and they would have a matching data set in the end. I don't know why the two users wouldn't just share the data.

> With regards to generating SAS scripts....I haven't touched SAS in over a decade. You guys will have to take that one up on your own. :)

If we can do the above, we can definitely do it for SAS. This actually seems practical, though it's possible @SimpleAddress4390 is the only user with this need. I could probably implement this, but we would need to consult with him for what this would look like.

> How much do you want the YAML form of the data dictionary? With what I've put together already, it shouldn't be hard to produce, but I'd like to make sure there's a market for such a product.

This is lower than low priority, there may be no market and I don't have a use case in mind. When I made a data dictionary, I didn't really like the data.frame format and a list was more intuitive. The YAML output looked nice and it could potentially interface well with something else - but this is not a need at this time.

**Comment by nutterb** [comment]
Based on the feedback, I'm submitted a pull request with the following

* `assembleCodebook` returns an object of class `c("redcapCodebook", "data.frame")`
* `as.list.redcapCodebook` will change that data frame to a list object.

YAML output isn't supported at this time, nor is there any tool to prepare a script for data processing.
