### ISSUE TITLE
httr2 upgrade

### ISSUE THREAD

**Issue by spgarbet** [vubiostat/redcapAPI#281]
httr is deprecated. At some point the package will be forced to migrate to httr.

**Comment by spgarbet** [comment]
I looked into this before and I dislike how many libraries it brings into dependency. Also the failure framework, this would bring about new modes of failure. However, I don't know how long httr will be maintained.

**Comment by nutterb** [comment]
I meant to respond to this last night.  According to their release article (https://www.tidyverse.org/blog/2023/11/httr2-1-0-0/)

>If you’re a current httr user, there’s no need to switch, as we’ll continue to maintain the package for many years to come

So probably not an urgent issue. 

And if you're concerned about expanded dependency chains, we could always look at RCurl and curl packages :) (I suspect either of those changes would be a bit more disruptive)

**Comment by spgarbet** [comment]
Let's shelve this then.
