### ISSUE TITLE
REDCap Version 14.0.2 Breakage

### ISSUE THREAD

**Issue by spgarbet** [vubiostat/redcapAPI#288]
We're seeing breakage in weird places that's not repeatable from 14.0.2 version rolling today. #286 was a result of this.

This ticket is to try and track down the remaining changes that are introduced by 14.0.2. 
 
In particular test-102-userRoleMethods-Functionality.R has changes. Comments in the test indicate that the API had issues previously and I think these have been fixed.

**Comment by spgarbet** [comment]
I just reran the tests and these two patches I just posted don't work and the interface is back to working like it did before I made them.

**Comment by spgarbet** [comment]
Every other time I run it, I'm getting different responses. I think these patches are on the shelf till it stabilizes.

**Comment by spgarbet** [comment]
I am convinced it's a caching problem. The requests for project information have about a 50% chance of reporting the right information if called immediately after a change.

**Comment by nutterb** [comment]
I assume you mean caching on the rcon object?

**Comment by spgarbet** [comment]
no server side.

**Comment by spgarbet** [comment]
Evidence: test suite makes a call that changes project information. It invalidates it's local cache and then requests that information. The copy it gets is stale and the test fails. Tests that rely on project information tend to fail randomly from run to run. If I slowly run them by hand they work. The best answer is that they have implemented some form of server side caching and it's causing project information to occasionally be stale.

**Comment by nutterb** [comment]
I can at least confirm behavior. I've run the test suite three times. The only tests that failed consistently were

test-103-userRoleAssignmentMethods-Functionality.R:90:5
test-103-userRoleAssignmentMethods-Functionality.R:106:5

So there might be something there. But everything else was sporadic.

**Comment by spgarbet** [comment]
They did implement caching. I'm finding 103 was missing some necessary cache flushes.

**Comment by spgarbet** [comment]
That last commit seems to get rid of a lot of issues. It still doesn't run reliably, and I think something similar is needed around file management.

**Comment by spgarbet** [comment]
The core REDCap team has fixed the issue on their side. I'm going to go ahead and submit this as a pull request for evaluation, but there is no rush. Please carefully consider if we should have these changes that seemed to help when meta data became unreliable.

**Comment by spgarbet** [comment]
It's broken again. I'm working with the core REDCap team to get the server fixed.
