### ISSUE TITLE
Remove stringr dependency

### ISSUE THREAD

**Issue by nutterb** [vubiostat/redcapAPI#29]
stringr::str_split_fixed is only used in `validate_import_select_dropdown_radio` and `validate_import_checkbox`. With a little care, it could be replaced with `strsplit` and this dependency could be removed. 

Note that strsplit_fixed has a feature that allows a string to be split into at most $n$ parts. We'll want to be careful with strsplit, as it would break a code-label mapping of "1, Tire, bicycle" into three parts, even though we want to map "1" to "Tire, bicycle."

**Comment by spgarbet** [comment]
```
> x
[1] "1,2,3,4,5"
> regmatches(x, regexec("([^,]*),(.*)", x, perl=TRUE))
[[1]]
[1] "1,2,3,4,5" "1"         "2,3,4,5" 
```

**Comment by nutterb** [comment]
That gives a cleaner look than what I came up with.  Thanks!
