### ISSUE TITLE
Field Labels for Checkbox Fields Should Match REDCap Label Style

### ISSUE THREAD

**Issue by nutterb** [vubiostat/redcapAPI#301]
Field labels for checkbox fields returned by `exportRecordsTyped` are identical for each level of the field

```
Rec <- exportRecordsTyped(rcon, 
                          fields = "checkbox_test")

library(labelVector)
get_label(Rec)[6:8]
[1] "Checkbox Example" "Checkbox Example" "Checkbox Example"
```

When the labeled headers are returned using the `rawOrLabelHeaders` API argument, they labels returned are

```
response <- makeApiCall(rcon, 
                        body = c(list(content = "record", 
                                    action = "export", 
                                    format = "csv", 
                                    rawOrLabelHeaders = "label"), 
                                 vectorToApiBodyList("checkbox_test", "fields")))

Rec <- read.csv(text = as.character(response), 
                na.strings = "", 
                check.names = FALSE)
names(Rec)

[1] "Checkbox Example (choice=Guitar)"   "Checkbox Example (choice=Ukulele)" 
[3] "Checkbox Example (choice=Mandolin)"
```

I would think the labels on checkbox fields should match the normal REDCap return. 

See also #296  and #299

**Comment by spgarbet** [comment]
Makes sense.

**Comment by nutterb** [comment]
> This is on the main branch now. How does this affect #296 and #299?

In both those issues, we were hitting limitations where the checkbox field limitation didn't give the detail of what the level was. Having this in place should simplify solutions in both those cases.
