### ISSUE TITLE
Minimize User Surprise on `raw_cast`

### ISSUE THREAD

**Issue by spgarbet** [vubiostat/redcapAPI#310]
When a user adds the argument `cast=raw_cast`, they expect all the raw data, but validation can trigger and eliminate values that do not validate. To the `.castRecords` function, we should add some content coupling to minimize user surprise when the override of the validation is forgotten (_we did this in our examples!_)

```
if(identical(cast, raw_cast) && identical(validation, .default_validate)) 
  validation <- function(x, ...) rep(TRUE, length(x))
```

**Comment by spgarbet** [comment]
Would you prefer?

```
if(identical(cast, raw_cast) && identical(validation, .default_validate)) 
  warn("'cast=raw_cast' needs 'validation=all_valid'")
```

And add a function 'all_valid'. This would keep the interface pure and not resort to automagic.

**Comment by obregos** [comment]
That is worrisome, it is important for users to be able to easily retrieve the raw data without a chance of validations eliminating values. I think this is a serious issue. I like the warning message for 'all_valid' to be used with 'raw_cast'.

However, I believe this type of dataset would be needed often so maybe a "exportRecordsRaw" might be better to make it as simple as possible for the user. Then again, I don't necessarily want to have too many different export functions. If we can bundle raw_cast and all_valid into its own flag, maybe cast=raw_data, I wouldn't mind that either. Raw_data and raw_cast might be too similar, though.

If we went the exportRecordsRaw route and a user wanted to export all the raw data but still wanted one or two fields to be cast as a specific data type, could they still perform that cast with exportRecordsRaw? And same with custom validations? Or would our recommendation in that case be to use exportRecordsTyped and perform custom cast and validations?

**Comment by spgarbet** [comment]
One has to make a choice, do you want the raw data or do you want the type cast algorithm. One could still use the type cast algorithm, but the validation argument goes hand in hand with the cast argument.

**Comment by nutterb** [comment]
You know, I've been overthinking this all day, but @obregos said something that sparked an idea.

Her idea for `exportRecordsRaw` is effectively what `exportRecords` will be in version 3.0.0. Plus, there's nothing stopping a user from using `exportRecords() |> recastRecords()` to do whatever they want with casting.

I think our best solution is to advise users who want raw data to patiently wait for 3.0.0, and give them hints to get raw data via `exportRecordsTyped` or how to do a direct data download using `makeApiCall`.

**Comment by spgarbet** [comment]
The problem with waiting is the issue effecting users now and it's confusing. At a minimum the documentation needs updating. We could fall back to the warning as suggested and add the 'all_valid' or what not. That's a fairly minimal change at this point.

**Comment by obregos** [comment]
Agreed, I like the 'all_valid' as we do need something for the time being.

**Comment by nutterb** [comment]
Sorry, I wasn't very clear.  I'm very much in favor of adding an `all_valid` as a stop-gap measure along with some documentation. I'm just not sold on adding warnings/messages as this point (but I'll leave that to your discretion)

So how do we feel about `exportRecordsTyped(rcon, validation = all_valid(), cast = raw_cast)` vs `exportRecordsTyped(rcon, validation = skip_validation(), cast = raw_cast)`?

**Comment by spgarbet** [comment]
Warnings are a mixed bag. I dislike adding them. The question is how many folks using raw_cast want default validations? I suspect few. 

> So how do we feel about exportRecordsTyped(rcon, validation = all_valid(), cast = raw_cast) vs exportRecordsTyped(rcon, validation = skip_validation(), cast = raw_cast)?

I was going to post with the same question. I had a 3rd option that is the "consistent" option, `raw_valdiation`. I like that one the least. Someone else needs to weigh in on preferred naming, @couthcommander @obregos ?

**Comment by couthcommander** [comment]
To me `skip_validation` is the clearest. My preference would be to use "NULL", even if a check internally swaps it out for `skip_validation` (or whatever).
