### ISSUE TITLE
Error in if (nrow(MissingFromFields) > 0) {: argument is of length zero

### ISSUE THREAD

**Issue by obregos** [vubiostat/redcapAPI#314]
I’m using R version 4.3.0 (2023-04-21)

Here’s a reprex of what I’m trying to do to use the new functionality:

```
options(keyring_backend=keyring::backend_file)

redcapAPI::unlockREDCap(connections = c(rcon_faa = "fa_anxiety"), url = 'https://redcap.partners.org/redcap/api/', keyring = "redcap_api_keys", envir = 1)

> <environment: R_GlobalEnv>

redcapAPI::exportRecordsTyped(rcon_faa)

> Error in if (nrow(MissingFromFields) > 0) {: argument is of length zero

```
Created on 2024-01-17 with [reprex v2.0.2](https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Freprex.tidyverse.org%2F&data=05%7C02%7Csavannah.obregon%40vumc.org%7C5614c0e3a28d4e78929208dc1799363a%7Cef57503014244ed8b83c12c533d879ab%7C0%7C0%7C638411194041123572%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=c%2F3949wJVELYdJI3hNIopq48vV6aP83n%2B5NOvEP7Brg%3D&reserved=0)

When I try the “old way” using redcapConnection and exportRecords I get this

```
rconn_old <- redcapAPI::redcapConnection(url = 'https://redcap.partners.org/redcap/api/', token = keyring::key_get(service = "redcapAPI", username = "fa_anxiety", keyring = "redcap_api_keys"))

redcapAPI::exportRecords(rcon = rconn_old)

> Please use exportRecordsTyped instead. exportRecords is will undergo breaking changes in version 3.0.0.

> Error in MetaData$form_name: $ operator is invalid for atomic vectors

```
Created on 2024-01-17 with [reprex v2.0.2](https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Freprex.tidyverse.org%2F&data=05%7C02%7Csavannah.obregon%40vumc.org%7C5614c0e3a28d4e78929208dc1799363a%7Cef57503014244ed8b83c12c533d879ab%7C0%7C0%7C638411194041133602%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=%2BQEL6ksxRDbvXFOMN103f9we6ZvC0Vy5dEVu6QfwuJc%3D&reserved=0)

**Comment by couthcommander** [comment]
I suspect the metadata function is returning "character(0)" (for reasons I don't know)

**Comment by obregos** [comment]
exportMetaData(rcon_faa) returns:
A 0x1 dataframe consisting of NA
[1] NA.
<0 rows> (or 0-length row.names)

**Comment by nutterb** [comment]
Oof.  That's bad. 

@spgarbet, is there any chance this is related to #290 and #297 ?

Also, is it possible to make a copy of this project with just the meta data so that we have an example project to play with and see if we can fix it?

**Comment by spgarbet** [comment]
The originator responded this morning and the symptoms are exactly like #290 and #297.

**Comment by couthcommander** [comment]
I realize we aren't able to reproduce this, but I wonder if something like this would get past it (example I've used for something else)?
```
  r <- RCurl::postForm(url, style = 'post')
  chk <- tryCatch(nchar(r), error = function(e) NULL)
  # remove unknown characters
  if(is.null(chk)) {
    r <- iconv(r, 'UTF-8', 'ISO-8859-1', '')
    r <- iconv(r, 'ISO-8859-1', 'UTF-8', '')
  }
```

**Comment by spgarbet** [comment]
Throw a SCREAMING hot warning in there and I think that would be the best solution.

**Comment by spgarbet** [comment]
Also I tested that snippet and the first iconv recreates the problem. It just needs the 2nd one.

**Comment by spgarbet** [comment]
```
> x <- "fa\xE7il,joe\n1, 2\n3, 4"
> Encoding(x) <- "UTF-8"
> iconv(x, 'UTF-8', 'ISO-8859-1')
[1] NA
> iconv(x, 'ISO-8859-1', 'UTF-8')
[1] "façil,joe\n1, 2\n3, 4"
```

**Comment by spgarbet** [comment]
Maybe this even?

```
  r <- RCurl::postForm(url, style = 'post')
  chk <- tryCatch(nchar(r), error = function(e) NULL)
  # fallback to 8859-1 for encoding
  if(is.null(chk)) Encoding(r) <- 'ISO-8859-1'
```

**Comment by spgarbet** [comment]
This `iconv(x, 'UTF-8', 'ISO-8859-1', sub='')` deletes the offending characters. It's the `sub` that drops it.

**Comment by spgarbet** [comment]
Relevant code from another library: https://github.com/yihui/xfun/blob/main/R/io.R#L20-L33

**Comment by spgarbet** [comment]
```
r <- RCurl::postForm(url, style = 'post')
chk <- tryCatch(nchar(r), error = function(e) NULL)
# remove unknown characters
# fallback to 8859-1 for encoding
if(is.null(chk))
{
  Encoding(r) <- 'ISO-8859-1'
  warning("Invalid characters encountered. Falling back to ISO-8859-1. Data loss may result.') 
}
```

**Comment by spgarbet** [comment]
I think the iconv pass is better that @couthcommander suggests. Just strip out the offending characters and move on. The REDCap GUI drops any field with offending characters, which does not present the actual data. However, I think what we should do is use the "sub" field and make the offending character "unknown" 

https://stackoverflow.com/questions/18760943/character-code-of-unknown-character-character-e-g-square-or-question-mark-romb

I think this works:

```
y <- "fail,joe\n1\xE7, 2\n3, 4"
Encoding(y) <- "UTF-8"
# Convert improper map character to Unknown
if(is.null(tryCatch(nchar(y), error=function(e) NULL)))
{
  y <- iconv(y, 'UTF-8', 'UTF-8', '\U25a1')
  warning("Invalid characters in project. Converting to Unicode '\U25a1'")
}
read.csv(con <- textConnection(y))
close(con)
```

Which looks like this:

```
> y <- "fail,joe\n1\xE7, 2\n3, 4"
> Encoding(y) <- "UTF-8"
> # Convert improper map character to Unknown
> if(is.null(tryCatch(nchar(y), error=function(e) NULL)))
+ {
+     y <- iconv(y, 'UTF-8', 'UTF-8', '\U25a1')
+     warning("Invalid characters in project. Converting to Unicode \U25a1")
+ }
Warning message:
Invalid characters in project. Converting to Unicode □ 
> read.csv(con <- textConnection(y))
  fail joe
1   1□   2
2    3   4
> close(con)
>
```

**Comment by spgarbet** [comment]
@dupontct Can you write us a patch set to do this for API calls right before it calls read.csv?

**Comment by dupontct** [comment]
The above solution will not work as httr stores the response as a RAW.  The default behavior of iconv (which httr calls to convert the raw to a string) is to return NA if it detects a invalid character.  So by the time it has gets to redcapAPI the value of the content is NA.

**Comment by couthcommander** [comment]
Good catch. If I'm following, `httr::as.character.response` > `content` > `parse_text` > `iconv`. Replicate all this behaviour with our own function to call `iconv` directly.

**Comment by spgarbet** [comment]
It ends up here: [content-parse.r](https://github.com/r-lib/httr/blob/df11e216f5e1a30f1bc8df8118e7cd983d9066f9/R/content-parse.r#L28)

We need a replacement for `httr::as.character.response`, let's call it `safe_character_response`. It's the `parse_text` that's at issue. 

Reference: [response.r](https://github.com/r-lib/httr/blob/main/R/response.r#L84)

**Comment by spgarbet** [comment]
Would this work?

```
safe_as_character_response <- function(response)
{
  stopifnot(is.response(x))
  
  type <- type %||% x$headers[["Content-Type"]] %||%
    mime::guess_type(x$url, empty = "application/octet-stream")
    
  if (is.path(x$content))
  {
    raw <- readBin(x$content, "raw", file.info(x$content)$size)
  } else
  {
    raw <- x$content
  }

  encoding <- guess_encoding(NULL, type)
  iconv(readBin(raw, character()), from = encoding, to = "UTF-8", '\U25a1')
}
```

**Comment by spgarbet** [comment]
Here's the shaved down version:

```
safe_as_character_response <- function(x, ...)
{
  type <- x$headers[["Content-Type"]]
  if(is.null(type)) type <- mime::guess_type(x$url, empty = "application/octet-stream")
    
  iconv(readBin(x$content, character()), type, 'UTF-8', '\U25a1')
}
```

**Comment by spgarbet** [comment]
```

R version 4.3.2 (2023-10-31) -- "Eye Holes"
Copyright (C) 2023 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

  Natural language support but running in an English locale

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

> ?`%||%`
No documentation for ‘%||%’ in specified packages and libraries:
you could try ‘??%||%’
> library(dplyr)

Attaching package: ‘dplyr’

The following objects are masked from ‘package:stats’:

    filter, lag

The following objects are masked from ‘package:base’:

    intersect, setdiff, setequal, union

> ?`%||%`

Restarting R session...

> ?`%||%`
No documentation for ‘%||%’ in specified packages and libraries:
you could try ‘??%||%’
> ?`rlang::%||%`
No documentation for ‘rlang::%||%’ in specified packages and libraries:
you could try ‘??rlang::%||%’
> ?`%||%
+ 1
+ ?`%||%`
+ ```
Error: attempt to use zero-length variable name
> ??`%||%`
> library(rlang)
> ?`%||%`
> mime::guess_type
function (file, unknown = "application/octet-stream", empty = "text/plain", 
    mime_extra = mimeextra, subtype = "") 
{
    file = basename(file)
    file = tools::file_ext(file)
    type = unname(c(mime_extra, mimemap)[tolower(file)])
    type[file == ""] = empty
    type[is.na(type)] = unknown
    if (any(i <- subtype != "")) {
        if (length(type) != length(file)) 
            stop("'subtype' must be of the same length as 'file'")
        type[i] = paste(type[i], subtype[i], sep = "; ")
    }
    type
}
<bytecode: 0x562b7363cb08>
<environment: namespace:mime>
> guess_encoding
Error: object 'guess_encoding' not found
> httr::guess_encoding
Error: 'guess_encoding' is not an exported object from 'namespace:httr'
> httr:::guess_encoding
function (encoding = NULL, type = NULL) 
{
    if (is.null(encoding)) {
        encoding <- tryCatch(error = function(err) NULL, parse_media(type)$params$charset)
    }
    if (is.null(encoding)) {
        message("No encoding supplied: defaulting to UTF-8.")
        return("UTF-8")
    }
    check_encoding(encoding)
}
<bytecode: 0x562b794b2920>
<environment: namespace:httr>
> httr:::guess_encoding("application/octet-stream")
Invalid encoding application/octet-stream: defaulting to UTF-8.
[1] "UTF-8"
> encoding <- httr:::guess_encoding(NULL, "application/octet-stream")
No encoding supplied: defaulting to UTF-8.
> 0.3 * 0.8
[1] 0.24
> 0.7 * 0.8
[1] 0.56
> safe_as_character_response <- function(x, ...)
+     iconv(readBin(x$content, character()), 'UTF-8', 'UTF-8', '\U25a1')
> x <- "fa\xE7il,joe\n1, 2\n3, 4"
> x <- as.raw("fa\xE7il,joe\n1, 2\n3, 4")
Warning messages:
1: NAs introduced by coercion 
2: out-of-range values treated as 0 in coercion to raw 
> x
[1] 00
> x <- charToRaw("fa\xE7il,joe\n1, 2\n3, 4")
> x
 [1] 66 61 e7 69 6c 2c 6a 6f 65 0a 31 2c 20 32 0a 33 2c 20 34
> safe_as_character_response(x)
Error in x$content : $ operator is invalid for atomic vectors
> x <- list(content=charToRaw("fa\xE7il,joe\n1, 2\n3, 4"))
> safe_as_character_response(x)
[1] "fa□il,joe\n1, 2\n3, 4"
> read.csv(safe_as_character_response(x))
Error in file(file, "rt") : cannot open the connection
In addition: Warning message:
In file(file, "rt") : cannot open file 'fa□il,joe
1, 2
3, 4': No such file or directory
> ?read.csv
> safe_as_character_response <- function(x, ...)
+     iconv(readBin(x$content, character()), 'UTF-8', 'UTF-8', '\U25a1')
> x <- list(content=charToRaw("fa\xE7il,joe\n1, 2\n3, 4"))
> read.csv(text=safe_as_character_response(x))
  fa.il joe
1     1   2
2     3   4
>
```

**Comment by spgarbet** [comment]
:bulb: In reading the w3 HTTP standards I think I know what happened. If one leaves the 'Content-Type: charset' unspecified the default is ISO-8859-1. All these tickets are showing up with characters in that set that don't map to UTF-8. I suspect that at some point one of the web servers didn't set this header. The data was converted to ISO-8859-1 as per the standard and recorded in these databases as a raw blob and the content type is reported as UTF-8 when it isn't.

**Comment by spgarbet** [comment]
@obregos  can you install 2.8.4 (`devtools::install_github('vubiostat/redcapAPI')`) and report if this solves the issue for you?

**Comment by spgarbet** [comment]
@nutterb  should we remove the drop_utf8 flag as it's no longer an issue and doesn't quite fit into the current as.data.frame method. R by default will change these to ".".

**Comment by nutterb** [comment]
As stated in https://github.com/vubiostat/redcapAPI/pull/320#issuecomment-1910856228

`drop_utf8` should probably go. It used to invoke `cleanseMetaData`, which was a very heavy handed approach to trying to deal with this issue (and I don't think it worked anyway). `exportMetaData` no longer uses `cleanseMetaData` and I deleted it in the 3.0.0 code

**Comment by spgarbet** [comment]
Okay. I'll prepare a patch to do that.

**Comment by spgarbet** [comment]
This is reported as working by the customer.

**Comment by baderstine** [comment]
I'm running v2.9.1 and getting this error: 
``` 
> exportRecordsTyped(rcon) 
Error in if (nrow(MissingFromFields) > 0) { : argument is of length zero

> exportRecords(rcon) 
Please use exportRecordsTyped instead. exportRecords is will undergo breaking changes in version 3.0.0.
Error in MetaData$form_name : $ operator is invalid for atomic vectors
```

What is the workaround?
