### ISSUE TITLE
Update `deleteRecords` with additional arguments

### ISSUE THREAD

**Issue by nutterb** [vubiostat/redcapAPI#315]
I noticed recently that `deleteRecords` does not have arguments for 

* `instrument`: character(1) or NULL, must be an existing instrument
* `event`: character(1) or NULL, must be an existing event
* `repeat_instance`: numeric(1) or NULL
* `delete_logging`: logical

**Comment by spgarbet** [comment]
One can delete logs?

**Comment by nutterb** [comment]
That's what the documentation says. Seems a little odd, and I wouldn't consider it best practice.

I'm not opposed to leaving that argument out of the interface. It can still be used through the api_param argument.

**Comment by spgarbet** [comment]
We can support it, but it goes against all my security training.
