### ISSUE TITLE
ExportRecordsTyped - not exporting all observations

### ISSUE THREAD

**Issue by idreamindata** [vubiostat/redcapAPI#316]
I have a REDCap project with 1,932 observations. When I used ExportRecordsTyped() only 18 observations are exported but when using ExportRecords, all 1,932 records are exported. Of note, the 18 records are records with a significant amount of missing data compared to the records not exported, data_entry_form_complete="Complete" for all records. 

Initially I used the most recent CRAN version but then installed the most recent development version from github and the error persists.

Happy to help troubleshoot and provide more information if it would be helpful.

**Comment by spgarbet** [comment]
exportRecordsTyped filters out empty rows by default (a commonly requested feature). Try it with `filter_empty_rows=FALSE` and let me know if that works for you.

**Comment by idreamindata** [comment]
That does not solve the problem. It isn't filtering out empty rows it is ONLY exporting primarily empty rows.

**Comment by nutterb** [comment]
Forgive me, but I'm going to bombard you with several things to try. It's hard to pinpoint an exact issue when we can't immediately access your data. It's a wide net to throw that will hopefully narrow down where the weirdness is happening. 

Also, I know you say you installed the development version. Please verify that you installed it after after about noon Eastern time (we merged in some new code about then)

1. does `Rec <- exportRecordsTyped(rcon)` give you a warning about data that failed validations? If so, what kind of content are you seeing from `reviewInvalidRecords(Rec)`?
2. What is returned by `exportRecordsTyped(rcon, validation = skip_validation, cast = raw_cast)`?
3. Do you have any project level missing data codes? `rcon$projectInformation()$missing_data_codes`
4. Do you have a secondary id field defined? `rcon$projectInformation()$secondary_unique_field

**Comment by spgarbet** [comment]
@nutterb We could expand that checklist and put it in the README under "Troubleshooting"

**Comment by idreamindata** [comment]
Ok. Today it ran as expected with no changes to my code! I wonder if I installed the dev version at the exact wrong time :) Thanks for all of you help and for the error checking process. I agree with @spgarbet that it would be great to have that process documented in the README troubleshooting section. I saved it for future issues. Thanks again!

**Comment by spgarbet** [comment]
If your project had a lot of checkboxes there was a patch released this week that fix a big with their handling. I have added those instructions to the README.
