### ISSUE TITLE
checkbox_suffix needs no version argument

### ISSUE THREAD

**Issue by nutterb** [vubiostat/redcapAPI#32]
The function has the `version` argument, but it never gets used in the function. We'll want to check where this gets called and make sure the functions calling it aren't passing it the version.  exportRecords and importRecords are the most likely to call this.  Maybe exportReports.

Also, https://github.com/vubiostat/redcapAPI/blob/main/R/checkbox_suffixes.R#L39 has a very impressively esoteric regular expression. While it's a cool one-liner, we might be better served with something us mere mortals can understand.  I propose

```
    opts <- meta_data$select_choices_or_calculations[meta_data$field_name %in% x]
    opts <- strsplit(opts, "[|]")
    opts <- unlist(opts)
    opts <- sub(",.+$", "", opts)
    opts <- trimws(opts)
    opts <- tolower(opts)
```

**Comment by spgarbet** [comment]
```
      opts <- strsplit(strsplit(checkbox_meta[i,'select_choices_or_calculations'],"\\s*\\|\\s*")[[1]],
                       "\\s*,\\s*")
      names(opts) <- sapply(opts, function(x) x[1])
      opts <- lapply(opts, function(x) x[2])
```

**Comment by nutterb** [comment]
I reached that conclusion, too, after seeing that I had parsed the select_choices_or_calculations four different places, each in a different way. 

I came up with: https://github.com/nutterb/redcapAPI/blob/Issue29-stringr/R/fieldChoiceMapping.R

Utilized at

https://github.com/nutterb/redcapAPI/blob/62670cc15a27c04d36c968e98232189b20d69a2b/R/allocationTable.R#L128
https://github.com/nutterb/redcapAPI/blob/62670cc15a27c04d36c968e98232189b20d69a2b/R/checkbox_suffixes.R#L41
https://github.com/nutterb/redcapAPI/blob/Issue29-stringr/R/checkbox_suffixes.R#L56
https://github.com/nutterb/redcapAPI/blob/Issue29-stringr/R/validateImport_methods.R#L442
https://github.com/nutterb/redcapAPI/blob/Issue29-stringr/R/validateImport_methods.R#L476
