### ISSUE TITLE
Data Query Support

### ISSUE THREAD

**Issue by spgarbet** [vubiostat/redcapAPI#321]
[Data Query on Redcap: User Guide](https://media.tghn.org/medialibrary/2020/01/nCoV_REDCap_Data_Query_v1.1_28Jan2020.pdf)

Need to add support for 'Data Query' module.

**Comment by spgarbet** [comment]
Data Query is coming up in more meetings. I mentioned this ticket and we can support it with some development.

**Comment by nutterb** [comment]
Maybe I'm missing something, but can this actually be supported right now?  I'm not seeing anything in the user guide you linked to that indicates the API can access these. I also can't find mention of it in the API documentation.

Could you elaborate on what support you hope to provide?

**Comment by spgarbet** [comment]
That's an interesting URL that it hits.

`prefix=vanderbilt_dataQuality` implies that the module prefix would be different across institutions. Which then forces that to be a parameter. 

Also this looks like only a pull, is there an API to push data into it? Also it would be interesting to see if it could be retrieved as a csv as there are simple routines to convert that into R internal to `redcapAPI`.

**Comment by spgarbet** [comment]
Maybe target this (assuming csv works). The pid argument is associated with the API_KEY, I don't know why that would be required. 

```
exportDataQuality(rcon, prefix, api_param = list(), csv_delimiter = ",", ...)
```

**Comment by spgarbet** [comment]
Merged.
