### ISSUE TITLE
Several functions don't properly parse vectors into arrays for the API call

### ISSUE THREAD

**Issue by nutterb** [vubiostat/redcapAPI#33]
* exportFieldsNames - doesn't handle `fields` correctly.
* exportArms - throws an error when `arms` is provided.
* exportMetaData - doesn't handle `fields` correctly
* exportMetaData - doesn't handle `forms` correctly

**Comment by spgarbet** [comment]
Even thought this is closed @nutterb does it relate at all to https://github.com/nutterb/redcapAPI/issues/32 ?

**Comment by nutterb** [comment]
I think it's more likely related to [nutterb/redcapAPI#37](https://github.com/nutterb/redcapAPI/issues/37)
