### ISSUE TITLE
Allow empty string in fields that should not have a value with method importMetaData()?

### ISSUE THREAD

**Issue by berryld1** [vubiostat/redcapAPI#345]
Current behavior with importMetaData - any field that *should* be empty, but has empty string instead of NA, errors.

Not that big a deal to replace with NA - but would be nice enhancement to this validation to allow either empty string or NA? Or, if it's redcap (i.e., not redcapAPI validations, per se, but The REDCap API) that objects to empty  string, help a user out and replace empty string with NA?

thanks for considering!

**Comment by spgarbet** [comment]
I think we could do this. Even if it's just to replace empty strings with NA inside the routine.

**Comment by spgarbet** [comment]
Complete with PR #347
