### ISSUE TITLE
redcapapi File Changes needed for REDCap Domain Migration

### ISSUE THREAD

**Issue by sharpwb** [vubiostat/redcapAPI#354]
redcapapi File Changes needed for REDCap Domain Migration

There are 8 lines of code that, if changed from redcap.vanderbilt.edu to redcap.vumc.org  result in a positive test of calling the new domain explicitly

those lines are found in these 3 files 
UsingOfflineConnections.Rmd ---> 1 occurence
helper-00-REDCapQACredentials.R---> 1 occurence
test-050-makeApiCall.R---> 6 occurences

**Comment by sharpwb** [comment]
I ran my test using R studio for Windows

**Comment by spgarbet** [comment]
Duplicate of #353
