### ISSUE TITLE
Summarize metadata

### ISSUE THREAD

**Issue by obregos** [vubiostat/redcapAPI#363]
We have a lot of metadata tools, maybe we need a "summary" method. I.e., summary(metadata) prints something nice.

The redcapTidieR package has this with it's `add_skimr_metadata()` function. https://github.com/CHOP-CGTInformatics/REDCapTidieR/blob/main/vignettes/REDCapTidieR.Rmd#L230

**Comment by spgarbet** [comment]
Looking through what this does is that it adds fields based on statistical summaries. It's not really a summary of the metadata. I see this as a concern outside the scope of this package. For example, kable, tangram and gt offer this functionality and a core part of their purpose is descriptive statistics of *any* data.
