### ISSUE TITLE
Date Validation (FIXME)

### ISSUE THREAD

**Issue by spgarbet** [vubiostat/redcapAPI#369]
At present a simple working date, date time, and date time seconds validations are included. They don't validate that the date specified is a an actual date, for example 2003-04-31 is accepted by the routines. A more complex [regex](https://regexlib.com/REDetails.aspx?regexp_id=112&AspxAutoDetectCookieSupport=1) is possible, but this would still allow any Feb 29th ignoring the leap year computation. Is there a way to validate a date quickly pre-cast that could be put into the existing validations. 

https://github.com/vubiostat/redcapAPI/blob/main/tests/testthat/test-053-fieldValidationAndCasting.R#L23

**Comment by spgarbet** [comment]
We have a lubridate dependency already. 

```
> ymd(c('2024-02-31', '2024-04-31', '2024-05-26'))
[1] NA           NA           "2024-05-26"
```

This validates dates. Maybe we should just do this and be done.

**Comment by nutterb** [comment]
The lubridate dependency exists for older code that is scheduled for removal with 3.0.0.  The 3.0.0 branch doesn't have this dependency. 

That doesn't mean we can't put it back in.  Just pointing out that we had made deliberate steps to remove it and so I'm not sure "we already have the dependency" is the right justification.  It should really be a question of whether carrying the dependency carries enough benefit.

**Comment by nutterb** [comment]
And, for what it's worth, the base R functions return something similar

```
> x <- c('2024-02-31', '2024-04-31', '2024-05-26')
> 
> as.Date(x, format = "%Y-%m-%d")
[1] NA           NA           "2024-05-26"
> 
> as.POSIXct(x, format = "%Y-%m-%d")
[1] NA               NA               "2024-05-26 EDT"
```

**Comment by spgarbet** [comment]
Reviewed with Cole. Here's the plan:

(1) Delete FIXME and leave defaults as is. 
(2) Create new method that a user can specify for validation: strictDateValidate, it uses the double call.
(3) Update documentation to point out the possible choice of validation to the user.

All in all, the strategy is to use the interface as designed and provide choices to the user.
