### ISSUE TITLE
Ignore Case Decision on True False validation (FIXME)

### ISSUE THREAD

**Issue by spgarbet** [vubiostat/redcapAPI#370]
Make a decision and implement. 

https://github.com/vubiostat/redcapAPI/blob/main/tests/testthat/test-053-fieldValidationAndCasting.R#L176-L177

**Comment by spgarbet** [comment]
My vote is that I don't really care about case. If a user hand wrote a "TrUe" as free form text and later the field was changed to be a TRUE/FALSE, the intent is still clear.

**Comment by spgarbet** [comment]
@nutterb Thoughts?

**Comment by nutterb** [comment]
I agree with that. Case insensitive seems preferable

**Comment by spgarbet** [comment]
Since this is just removing a comment, I skipped the PR.
