### ISSUE TITLE
Fields with _complete being cast incorrectly

### ISSUE THREAD

**Issue by obregos** [vubiostat/redcapAPI#380]
The moca4_complete field is a radio button coded with values  "1, Yes, Completely | 2, Yes, Partially | 0, No". The metadata recognizes this but the _complete at the end of the field results in it being cast with completion field values (Complete, Incomplete or Unverified)

```
> ecid_conn$metadata()[ecid_conn$metadata()$field_name == 'moca4_complete',]$select_choices_or_calculations
[1] "1, Yes, Completely | 2, Yes, Partially | 0, No"

> exportRecordsTyped(ecid_conn)
record_id moca4_complete month_moca_complete
1         2     Unverified            Complete
2         3       Complete            Complete
3         4     Incomplete            Complete

```

**Comment by spgarbet** [comment]
I suspect this is too greedy: https://github.com/vubiostat/redcapAPI/blob/main/R/assembleCodebook.R#L227-L229

**Comment by spgarbet** [comment]
Fix merged.
