### ISSUE TITLE
Warning on Valid Secondary ID

### ISSUE THREAD

**Issue by spgarbet** [vubiostat/redcapAPI#393]
When asking for form data when secondary ID is defined it gives the secondary ID warning. The secondary ID is defined for the project, just not part of the form. 

Proposal:

(1) Remove warning
(2) Make sure form includes it as a system field.

**Comment by jubilee2** [comment]
<img width="839" alt="Screenshot 2024-07-05 at 9 52 45 AM" src="https://github.com/vubiostat/redcapAPI/assets/5558405/b92330f0-d23c-4505-9fcf-82105a91ff93">

Based on the REDCap document, it is important to note the following:
 - The field described is not designed to serve as a secondary ID but rather as a unique field. This means its primary purpose is to ensure that the value entered is unique across all records in the project.
 - This unique field functionality may not work 100% effectively for all types of REDCap databases. There could be limitations or exceptions depending on the specific database configuration.

**Comment by spgarbet** [comment]
That is an interesting observation, it's not an additional part of the unique key but a 2nd alternative unique key, and this key may not exist on a form meaning it's not truly unique in the project. In this case the warning is appropriate.
