### ISSUE TITLE
update roxygen, imports in redcapAPI-package.R

### ISSUE THREAD

**Issue by couthcommander** [vubiostat/redcapAPI#395]
royxgen2 isn't generating "importFrom" in NAMESPACE. These should be defined in "redcapAPI-package.R".

**Comment by couthcommander** [comment]
After further investigation, `importFrom` was in individual files. This approach is fine, though I prefer storing all in a single location. Additionally many imports were missing. This too is fine, in the sense that CHECK doesn't fail, but it's probably bad practice.

**Comment by spgarbet** [comment]
The thinking in roxygen was that importFrom would be closest to the usage. With the fan-in of documentation it drifts further and further away.
