### ISSUE TITLE
consider dropping "httr" dependency

### ISSUE THREAD

**Issue by couthcommander** [vubiostat/redcapAPI#397]
Package "httr" is deprecated for "httr2", which adds dependency bloat. Ideally we could re-implement needed functionality with "curl" (as does "httr").

These functions would need a replacement:
 * httr::config
 * httr::content
 * httr::POST
 * httr::set_config
 * httr::timeout
 * httr::upload_file

**Comment by spgarbet** [comment]
I looked at folding httr into our package and those 6 dependencies pull in a tree of files.

**Comment by spgarbet** [comment]
httr2 has a huge number of dependencies thus it is not preferable to upgrade.

**Comment by spgarbet** [comment]
This is also a dup of #281

**Comment by spgarbet** [comment]
I think stripping back to straight RCurl might be easier.
