### ISSUE TITLE
 Discussion: Adding GitHub Action for R CMD check on PRs

### ISSUE THREAD

**Issue by jubilee2** [vubiostat/redcapAPI#398]
### Background
I am considering adding a GitHub Action to run `R CMD check` on every pull request. This action would ensure that our R package is tested across multiple platforms (macOS, Linux, and Windows) before merging any changes.

### Proposal
- Implement a GitHub Action workflow that runs `R CMD check` on:
  - macOS
  - Linux
  - Windows

### Benefits
- Ensures code quality and compatibility across different operating systems.
- Automates the testing process, reducing manual effort.
- Helps catch platform-specific issues early in the development process.

### Implementation
We can use the `r-lib/actions` GitHub Actions for this purpose. Here is a basic example of the workflow file: https://github.com/jubilee2/redcapAPI/blob/main/.github/workflows/r-cmd-check.yml

**Comment by spgarbet** [comment]
I did the for the r-yaml package recently and it works well. Make sure the .Rbuildignore file contains the CI files.
