### ISSUE TITLE
Unable to delete repeated instances with deleteRecords()

### ISSUE THREAD

**Issue by bwaheed22** [vubiostat/redcapAPI#409]
I am trying to delete a specific repeated instance for a record with `deleteRecords()` but when I specify the record ID, instrument name and repeated instance in the function call, it deletes the entire record. 

This example deletes all of record 113 instead of just repeat instance 13 in instrument 'instrument name':

`
deleteRecords(rcon = rc, 
records = '113', 
instrument = 'instrument name',
repeat_instance = '13'
)
`

How do I use this function to delete individual repeated instances? Can I use this function for this purpose or is there a different way to do it?

Any help is greatly appreciated!

**Comment by nutterb** [comment]
Could you report back what is returned by `rc$projectInformation()$is_longitudinal`.  It should be either 0 (classic project) or 1 (longitudinal project). The REDCap documentation indicates that the `event` argument is mandatory if `instrument` is provided. (I'm expecting your project is not longitudinal)

**Comment by nutterb** [comment]
I will also add, I have been able to get this to delete a single instance as long as I provide the arguments `arm`, `event`, `instrument`, and `repeat_instance`. 

However, if I omit any of these arguments, it deletes the data for the entire record. I will update the documentation to describe this behavior.

**Comment by nutterb** [comment]
Yes, I'm hoping that will work.  I will try to set up a non-longitudinal project to test against this evening.

Please let me know if your use of those arguments produces results.

**Comment by jubilee2** [comment]
Hi @bwaheed22 ,

I tested the method, and it works for my project. Our REDCap is running on v14.6.4, and the is_longitudinal is 0. Here are the arguments I used:

```R
deleteRecords(test2, records = '13', instrument = 'form2', repeat_instance = 2)
```

**Comment by spgarbet** [comment]
@bwaheed22 Did this ever get resolved for you?

**Comment by spgarbet** [comment]
No response from user. Closing as completed.
