### ISSUE TITLE
Strategies for REDCap timeouts

### ISSUE THREAD

**Issue by spgarbet** [vubiostat/redcapAPI#41]
We needs a couple enhancements to deal with REDCap timeouts. 

1) A retry flag on methods. This would be the number of retries allowed for a call. Each call should be at a geometric progression of intervals, e.g. 3 seconds, 4 seconds, 8 seconds, 27 seconds, 1.4 minutes, 4 minutes, 12 minutes ... Maybe the progression value is taking from options. 
2) It might be possible to also expose socket timeout values. I don't know how feasible this is.

**Comment by spgarbet** [comment]
From https://github.com/nutterb/redcapAPI/issues/10

A user said he could manipulate socket timeouts in python with this code: https://github.com/AMP-SCZ/utility/blob/2517c9ceaede6e8bb67cbae50e9b1e7cbdd4be32/import_records_all.py#L5-L32

**Comment by spgarbet** [comment]
https://github.com/nutterb/redcapAPI/issues/18

**Comment by spgarbet** [comment]
https://gist.github.com/spgarbet/e6362266fb349ff4e450079e36eb2b1d

**Comment by nutterb** [comment]
Here's an idea for how to handle these.  This link goes to a pull request on my repo (so you can see the changes) https://github.com/nutterb/redcapAPI/pull/45

The full branch is at https://github.com/nutterb/redcapAPI/tree/issue-41-timeout

**Comment by spgarbet** [comment]
This looks really nice. I like this strategy and code.

**Comment by nutterb** [comment]
Do you have any suggestions on how to test this?  I'm not sure how to force a time out, or any other error we might want to catch with this.

**Comment by nutterb** [comment]
That's extraordinarily helpful. Thank you!  

I just made the following adjustments, based on the list of status codes:

* remove regex comparison and determine eligibility for retry based on the status code. 
* It's somewhat silly, but I put the eligibility check into its own unexported method. https://github.com/nutterb/redcapAPI/blob/issue-41-timeout/R/makeApiCall.R#L199-L211. But as a separate method, I can write tests against it without actually having to call the API. Essentially, we test that we recognize the desired status codes and assume we code the break correctly (pretty safe bet.  test code at https://github.com/nutterb/redcapAPI/blob/issue-41-timeout/tests/testthat/test-makeApiCall.R#L46-L74)

I think these tests ought to give  us enough confidence that it will behave the way we intend when it encounters the status codes, without having to monkey around with trying to force one of them to occur. 

If you're comfortable with this, let me know and I'll finish up tests, checks, etc, before preparing a pull request upward.

**Comment by spgarbet** [comment]
If the existing tests pass and we have more I think this is a go.
