### ISSUE TITLE
Failure (test-801-changedRecords.R:22:5): Returns records known to change in prior tests

### ISSUE THREAD

**Issue by sharpwb** [vubiostat/redcapAPI#411]
Experienced this error while running the internal test suite,  testing new redcap version 14.6.5 on windows 10 using R studio and R version 4.4.1

Failure (test-801-changedRecords.R:22:5): Returns records known to change in prior tests
all(recs %in% x$deleted) is not TRUE

`actual`:   FALSE
`expected`: TRUE 

Shawn commented that this is a false positive and hard to reproduce

**Comment by sharpwb** [comment]
same erroe kust occurred using ubunto R Studio with 4.4.1

**Comment by jubilee2** [comment]
I tested this on my end and encountered the same issue.

**Comment by spgarbet** [comment]
I have a suspicion that REDCap's logging mechanism doesn't keep up with data changes. I.e., I'm thinking there is a lag time between the operations in the test suite and when it shows up in logging. If this is true then a delay might fix it.
