### ISSUE TITLE
Dependency Update: R Version and Hmisc Compatibility

### ISSUE THREAD

**Issue by jubilee2** [vubiostat/redcapAPI#428]
The current dependency for RedcapAPI is R (>= 3.5.0). Considering Hmisc's recent updates, we'd like to discuss:

1. Updating RedcapAPI's R dependency to match Hmisc's (>= 4.0.0).
2. Implementing conditional code changes for backward compatibility (e.g., Hmisc <= x.x.x).
3. Potential implications for users' environments.

Questions

- What are the benefits and drawbacks of updating the R dependency?
- How will conditional code changes impact performance and maintainability?
- Are there alternative solutions to ensure compatibility?

**Comment by spgarbet** [comment]
Has there been an issue relating to this? If so can you give details?

**Comment by jubilee2** [comment]
https://github.com/vubiostat/redcapAPI/actions/runs/12371755879/job/34528539455#step:7:195

**Comment by spgarbet** [comment]
If this is the auto CHECK on github issue the changes suggested don't fix the real problem. 

(1) redcapAPI does not depend on Hmisc. It is only a suggestion. 
(2) Hmisc made a breaking change.
(3) The auto CHECK on github checks the present and last 3 versions of R using CMD CHECK, and it install Hmisc as part of this. 
(4) Hmisc fails from 3 versions ago now. 

If we make the recommend version constraint a user who has an older version of R and is not using Hmisc would be forced to upgrade. redcapAPI isn't broken with these older versions. 

Solution is to remove old-rel-3 from the CHECK set or remove Hmisc from the installed test environment.

**Comment by spgarbet** [comment]
A fix for the github CHECK issue is included in PR for #413

**Comment by spgarbet** [comment]
Fixed by the last PULL request.
