### ISSUE TITLE
Update to curl call needed

### ISSUE THREAD

**Issue by spgarbet** [vubiostat/redcapAPI#429]
https://github.com/jeroen/curl/issues/359#issuecomment-2564847880

**Comment by spgarbet** [comment]
@couthcommander can you look at this and advise?

**Comment by jeroen** [comment]
There is no update needed in the package. This bug appears when people are running a very outdated version of MacOS. In this case they need to update MacOS.

**Comment by spgarbet** [comment]
Ah. Thanks for the clarification. I'm still groggy from holiday.
