### ISSUE TITLE
redcapAPI currently does not pull factor labels for REDCap fields of "sql" type

### ISSUE THREAD

**Issue by omair-a-khan** [vubiostat/redcapAPI#46]
For REDCap fields that are of "sql" type, it would be helpful if the metadata could include the labels associated with the numerical values in the corresponding SQL database. For example, see the variable `med01_name` in the tibble below:

![Screenshot 2023-03-21 at 12 57 25 PM](https://user-images.githubusercontent.com/9165116/226700307-a0d5bc25-ddb5-41ca-8870-f7141367f3ef.png)

The corresponding metadata is as follows (focus on the `select_choices_or_calculations` column):

![image](https://user-images.githubusercontent.com/9165116/226700777-3bdf2220-d9c4-4d6a-83f8-edf9f066684a.png)

redcapAPI references the corresponding database's project ID and field name, but does not pull in the levels and labels as it would if it were, for example, a dropdown field (e.g, `"1, Yes | 0, No | -8888, Prefer not to answer"`).

**Comment by omair-a-khan** [comment]
@nutterb, I'm getting all the labels using this code!

**Comment by nutterb** [comment]
At the risk of sounding glum--I was afraid of that. 

But it at least means we can get there.

**Comment by spgarbet** [comment]
Issue #10 and it's inclusion in 2.7.0 will not solve this issue. It was a bridge too far. This needs a bit more careful focus.

**Comment by spgarbet** [comment]
I opened a support request to see if there was an API call that would return the choices for a 'sql' field. I suspect the answer is no, but it's worth a shot.

**Comment by spgarbet** [comment]
Maybe we could make second "label" call and use that. Since we have no means to validate anything it returns, the "validation" step would just be "return rep(length(x), TRUE)". I suspect what we do is have a function call that calls  export records API with (rcon, cast=raw_cast, fields=<all sql fields>, labels=TRUE) and turn those into choice fields. Then the case can proceed by user specification.

**Comment by nutterb** [comment]
I've considered that, and it's the approach I dislike the least. I wasn't sure if that would work when record IDs get hashed, but from the look of it, record IDs are hashed the same way on each call and across sessions. (that kind of surprised me. I thought the purpose was to break the link between the subject and the identifier, which this doesn't really do. It would seem I misunderstood the intent of the hash). 

So am I understanding you correctly?  You're suggesting we can 

1. export the raw (coded) sql field values
2. run a second API call for the labelled sql field values
3. Use the two sets of values to create a codebook for the sql fields
4. Use the codebook to cast the field

If I've understood correctly, I think that's overly complex and potentially incomplete. We can't guarantee that we have the full codebook; we will only have the parts of the codebook that appear in the data (which is, admittedly, enough for the immediate need). 

I would think it easier to run the two API calls, merge the labelled data to the raw data and either 
1. leave it be, they can have two columns, or 
2. Design the cast function to cast the coded column to NULL if labelled is requested, and vice versa.

I haven't thought through how to write that casting function yet, so it's possible that isn't as feasible as it seems on the surface.

**Comment by spgarbet** [comment]
Creating a cached code book sounds like the right approach. Solve the problem once and keep it for all. It should get flushed with the metadata, or even be an extension of the metadata.

**Comment by nutterb** [comment]
Add an `rcon$push_metadata(m)` method that pushes `m` into the cached metadata slot and you could probably work up this (pseudocode)

```
makeSqlCodebook <- function(rcon, records, api_body, api_param, config){
  MetaData <- rcon$metadata()
  
  id_fields <- MetaData$field_name[1]
  if ("redcap_event_name" %in% names(records)) id_fields <- c(id_fields, "redcap_event_name")
  
  ### Do we need to handle secondary identifier field? (rcon$projectInformation()$secondary_unique_field)
  
  sql_fields <- MetaData$field_name[MetaData$field_type == "sql"]
  
  api_body$rawOrLabel <- "label"
  
  api_body <- [!grepl("^fields", names(api_body))]
  api_body <- c(api_body, 
                vectorToApiBodyList(c(id_field, sql_fields))
  
  response <- makeApiCall(rcon, 
                          body = c(api_body, api_param), 
                          config = config)
  
  SqlData <- read.csv(text = as.character(response), 
                      stringsAsFactors = FALSE, 
                      na.strings = "", 
                      colClasses = "character", 
                      sep = csv_delimiter)
  
  for (i in sql_fields){
    ThisData <- merge(records[c(id_fields, sql_fields[i])], 
                      SqlData[c(id_fields, sql_fields[i])], 
                      by = id_fields, 
                      all.x = TRUE)
    
    this_codebook <- 
    # Whatever magic maps the code-label pairings to code1, label1 | code2, label2 | ... | coden, labeln
    
    MetaData$select_choices_or_calculations[MetaData$field_name == sql_fields[i]] <- 
      this_codebook
  }
  
  rcon$push_metadata(MetaData)
}
```

This may mean we have to require the record ID and secondary field identifier be included

but if this were place right after the API call to get the `Raw` data, I would expect everything after would (might have to change the default sql cast type)

**Comment by spgarbet** [comment]
This looks like the right idea. Your speed at coding up these ideas is incredible.

**Comment by nutterb** [comment]
It's one of those gifts that comes with an equal curse. Able to recognize good ideas and map out broad strategies to get to my goal. But often miss some of the most salient details.

I once put a computer together for a friend. It wouldn't turn on. I spent two hours troubleshooting that thing to finally discover that I hadn't connected the CPU power cable 

See also, no calc field in the database.

**Comment by nutterb** [comment]
Oh...and another example...I can't create a SQL field. Any chance someone could rig one of those up for me to test against?

**Comment by spgarbet** [comment]
I can't do it either. I have to put in a request and the REDCap team has to do it. We need to have it clearly defined what we want up front and I can put that in.

**Comment by spgarbet** [comment]
I see there's a branch out there with code you'd worked on that is now terribly behind main. Was this essentially waiting on a test for it? We could always get @omair-a-khan to test with his database. It's not ideal, but we could go ahead an finished this out to some degree.

**Comment by nutterb** [comment]
The code in that branch builds a choices mapping by making a labelled and unlabelled call to the API and using those to build a look up table between the codes and labels. Which...works?  kind of?

But in a phone conversation, we seemed more interested in maybe using the approach described in https://github.com/nutterb/redcapAPI/issues/23

That wasn't something we thought we could do on the timeline we wanted for exportRecordsTyped.

So, it's still a question of how do we want to get the information we need. But even if we want to use the strategy in that branch, there has been so much work done that it's probably easier to start over.

**Comment by nutterb** [comment]
Good morning, @omair-a-khan ! 

We've recently made some progress toward being able to accommodate sql fields.  I don't have a sql field I can test against, at the moment, and was hoping you would be willing to try this out for us. If you're willing, would you please do the following?

1. run `devtools::intall_github("vubiostat/redcapAPI", ref = "issue-46-sql-casting")`
2. run `exportRecordsTyped(rcon, cast = list(sql = castLabel))`. This should produce the labeled values for SQL fields.
3. run `exportRecordsTyped(rcon, cast = list(sql = castCode))`. This should produce the coded values for SQL fields.
4. Report back on how it went.

If it doesn't produce the intended results, I'll press harder to get a SQL field set up in one of our projects so I can trouble shoot it, but I wouldn't anticipate that being done before Thanksgiving.

Thanks

**Comment by spgarbet** [comment]
Hurray! PR handling this has been merged.
