### ISSUE TITLE
export Reports not working

### ISSUE THREAD

**Issue by obregos** [vubiostat/redcapAPI#48]
In a project where a report has and ID of '1' and name of '1' the following code does not export the report:

`report <- exportReports(rcon, 1)`

Instead it returns error message:
```
Error in redcap_error(x, error_handling) : 
  403: ERROR: The API request cannot complete because report_id=1 does not belong to this project.
```

In the API Playground the report is able to be exported correctly.

**Comment by nutterb** [comment]
I think it's supposed to be this number (357209)

![image](https://user-images.githubusercontent.com/1848445/226737430-ba04e041-c39e-4077-8d83-7c03f153db32.png)

try exportReports(rcon, record_id = '357209')

It took me a minute. I wasn't sure what the REDCap documentation meant by 'report list page' in 

> the report ID number provided next to the report name on the report list page

**Comment by obregos** [comment]
Thank you! That worked.
