### ISSUE TITLE
importRecords compatibility with exportRecords

### ISSUE THREAD

**Issue by spgarbet** [vubiostat/redcapAPI#72]
This is just an open question. With `exportRecordsTyped` near complete, what can be done to make it compatible with importRecords? Is anything required? One issue I can see is the need to drop the mChoice variables.

**Comment by spgarbet** [comment]
The rabbit hole is deep and forbidding. User flexibility for the path back in the long run is a good idea, but ultimately has fewer use cases. The complexity allowed for data export is for doing things like having an export go straight into an ARIMA model for example. It's going to be mostly be used in analysis. However, it is not uncommon for folks to push up things like oddly coded data (e.g. -9=NA). In that case, they are managing their own code book. Those pushing data back up are generally "generators" or "modifiers" and typically will use the data in a closer to raw form in general.

**Comment by nutterb** [comment]
I think I will recommend relaxing the constraint at https://github.com/vubiostat/redcapAPI/blob/main/R/importRecords.R#L218-L224. Instead of returning a hard error, just send back the unrecognized names with a warning/message that they are being removed from the import. That should catch any mChoice fields as well as other fields that don't belong in the project.  

Should be pretty easy to replace that coll$push with a message.

**Comment by spgarbet** [comment]
That sounds like a great plan.

**Comment by spgarbet** [comment]
@nutterb where did we land on this? Is this a close this one and open something targeted on the new problem?

**Comment by nutterb** [comment]
I think that is the right idea. The standard output of exportRecordsTyped seems to play nicely with importRecords as it exists.

The edges where importRecords doesn't play nicely are a separate problem. It might be worthwhile to come back and reevaluate much of how that function works (perhaps capturing a validation report, or implementing the casting functions, for instance)

But we're no worse off than we were before

**Comment by spgarbet** [comment]
Okay. I'll close this for now then and we'll dive in when something pops up.
