### ISSUE TITLE
Develop an importMetaData function

### ISSUE THREAD

**Issue by nutterb** [vubiostat/redcapAPI#81]
Provide the following features

* column names match the API export metadata columns
* enforce valid field names are lowercase letters and underscore characters
* enforce valid form names are lowercase letters and underscore characters
* enforce valid field types. Needs to be configurable in case new field types are added.
* enforce select_choices format. Note, format is different for multiple choice and sliders
* enforce select_choices only for (dropdown, radio, checkbox, sql, slider)
* enforce text_valdiation type. Needs to be configurable. Different institutions may have different options
* all elements between brackets in branching logic need to be either a unique_event_name or field_name

A separate utility to map the UI download column names to the API download column names could be useful

function call

```
importMetaData <- function(rcon, 
                           data, 
                           ..., 
                           field_types = REDCAP_FIELD_TYPES, # exported constant
                           validation_types = REDCAP_METADATA_VALIDATION_TYPE, # exported constant
                           config = list(), 
                           api_param = list()){...}
```

**Comment by spgarbet** [comment]
Close with #85
