### ISSUE TITLE
mChoiceCast [post process records]

### ISSUE THREAD

**Issue by spgarbet** [vubiostat/redcapAPI#88]
Move mChoice processing to a post-processing `mChoiceCast` function in concordance with design in #86.

**Comment by spgarbet** [comment]
@nutterb Having some difficulties refactoring this. There were two pieces of information available before "fields" and "RawRecords" I don't know where to pull these from in a post-process without making more calls. Ideas?

**Comment by nutterb** [comment]
I think for fields, you want

```
FieldNames <- rcon$fieldnames()
fields <- names(Records)
fields <- FieldNames$original_field_name[FieldNames$export_field_name %in% fields]
fields <- unique(fields)
```

`fields` in exportRecordsTyped is the fields list passed to the API (so without the ___suffix). 

I'm actually working on a recastRaw casting function now that might help with this. I think that would be easier than trying to write this to recognize any of c("Checked", "1", "yes", coded, labelled).

**Comment by nutterb** [comment]
@spgarbet I can confirm,

 ```
FieldNames <- rcon$fieldnames()
fields <- FieldNames$original_field_name[FieldNames$export_field_name %in% colnames(Records)]
fields <- unique(fields)
```

gets you the field names you want. and then to get Raw, use 

```
recastRecords(Records, rcon, fields = names(Records), cast = list(checkbox = recastRaw)) 
```

**Comment by spgarbet** [comment]
Close with #101
